
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Oct 30 2025 14:19:23 IST (Oct 30 2025 08:49:23 UTC)

// Verification Directory fv/fft_4pt 

module fft_4pt(clk, rst_n, data_valid_in, x0_r, x0_i, x1_r, x1_i, x2_r,
     x2_i, x3_r, x3_i, data_valid_out, X0_r, X0_i, X1_r, X1_i, X2_r,
     X2_i, X3_r, X3_i);
  input clk, rst_n, data_valid_in;
  input [15:0] x0_r, x0_i, x1_r, x1_i, x2_r, x2_i, x3_r, x3_i;
  output data_valid_out;
  output [17:0] X0_r, X0_i, X1_r, X1_i, X2_r, X2_i, X3_r, X3_i;
  wire clk, rst_n, data_valid_in;
  wire [15:0] x0_r, x0_i, x1_r, x1_i, x2_r, x2_i, x3_r, x3_i;
  wire data_valid_out;
  wire [17:0] X0_r, X0_i, X1_r, X1_i, X2_r, X2_i, X3_r, X3_i;
  wire [17:0] X1_r_w;
  wire [17:0] X0_r_w;
  wire [17:0] X0_i_w;
  wire [17:0] X1_i_w;
  wire [17:0] X3_i_w;
  wire [17:0] X2_r_w;
  wire [17:0] X3_r_w;
  wire [17:0] X2_i_w;
  wire [16:0] B_i;
  wire [16:0] B_i_reg;
  wire [16:0] A_i;
  wire [16:0] A_i_reg;
  wire [16:0] C_r;
  wire [16:0] C_r_reg;
  wire [16:0] A_r;
  wire [16:0] A_r_reg;
  wire [16:0] D_i;
  wire [16:0] D_i_reg;
  wire [16:0] B_r;
  wire [16:0] B_r_reg;
  wire [16:0] D_r;
  wire [16:0] D_r_reg;
  wire [16:0] C_i;
  wire [16:0] C_i_reg;
  wire [15:0] x1_i_reg;
  wire [15:0] x1_r_reg;
  wire [15:0] x3_r_reg;
  wire [15:0] x0_i_reg;
  wire [15:0] x0_r_reg;
  wire [15:0] x2_i_reg;
  wire [15:0] x3_i_reg;
  wire [15:0] x2_r_reg;
  wire ADD_TC_OP66_n_0, ADD_TC_OP66_n_2, ADD_TC_OP66_n_4,
       ADD_TC_OP66_n_6, ADD_TC_OP66_n_8, ADD_TC_OP66_n_10,
       ADD_TC_OP66_n_12, ADD_TC_OP66_n_14;
  wire ADD_TC_OP66_n_16, ADD_TC_OP66_n_18, ADD_TC_OP66_n_20,
       ADD_TC_OP66_n_22, ADD_TC_OP66_n_24, ADD_TC_OP66_n_26,
       ADD_TC_OP66_n_28, ADD_TC_OP66_n_30;
  wire ADD_TC_OP66_n_32, ADD_TC_OP66_n_34, ADD_TC_OP68_n_0,
       ADD_TC_OP68_n_2, ADD_TC_OP68_n_4, ADD_TC_OP68_n_6,
       ADD_TC_OP68_n_8, ADD_TC_OP68_n_10;
  wire ADD_TC_OP68_n_12, ADD_TC_OP68_n_14, ADD_TC_OP68_n_16,
       ADD_TC_OP68_n_18, ADD_TC_OP68_n_20, ADD_TC_OP68_n_22,
       ADD_TC_OP68_n_24, ADD_TC_OP68_n_26;
  wire ADD_TC_OP68_n_28, ADD_TC_OP68_n_30, ADD_TC_OP68_n_32,
       ADD_TC_OP68_n_34, ADD_TC_OP70_n_0, ADD_TC_OP70_n_2,
       ADD_TC_OP70_n_4, ADD_TC_OP70_n_6;
  wire ADD_TC_OP70_n_8, ADD_TC_OP70_n_10, ADD_TC_OP70_n_12,
       ADD_TC_OP70_n_14, ADD_TC_OP70_n_16, ADD_TC_OP70_n_18,
       ADD_TC_OP70_n_20, ADD_TC_OP70_n_22;
  wire ADD_TC_OP70_n_24, ADD_TC_OP70_n_26, ADD_TC_OP70_n_28,
       ADD_TC_OP70_n_30, ADD_TC_OP70_n_32, ADD_TC_OP70_n_34,
       ADD_TC_OP72_n_0, ADD_TC_OP72_n_2;
  wire ADD_TC_OP72_n_4, ADD_TC_OP72_n_6, ADD_TC_OP72_n_8,
       ADD_TC_OP72_n_10, ADD_TC_OP72_n_12, ADD_TC_OP72_n_14,
       ADD_TC_OP72_n_16, ADD_TC_OP72_n_18;
  wire ADD_TC_OP72_n_20, ADD_TC_OP72_n_22, ADD_TC_OP72_n_24,
       ADD_TC_OP72_n_26, ADD_TC_OP72_n_28, ADD_TC_OP72_n_30,
       ADD_TC_OP72_n_32, ADD_TC_OP74_n_0;
  wire ADD_TC_OP74_n_2, ADD_TC_OP74_n_4, ADD_TC_OP74_n_6,
       ADD_TC_OP74_n_8, ADD_TC_OP74_n_10, ADD_TC_OP74_n_12,
       ADD_TC_OP74_n_14, ADD_TC_OP74_n_16;
  wire ADD_TC_OP74_n_18, ADD_TC_OP74_n_20, ADD_TC_OP74_n_22,
       ADD_TC_OP74_n_24, ADD_TC_OP74_n_26, ADD_TC_OP74_n_28,
       ADD_TC_OP74_n_30, ADD_TC_OP74_n_32;
  wire ADD_TC_OP76_n_0, ADD_TC_OP76_n_2, ADD_TC_OP76_n_4,
       ADD_TC_OP76_n_6, ADD_TC_OP76_n_8, ADD_TC_OP76_n_10,
       ADD_TC_OP76_n_12, ADD_TC_OP76_n_14;
  wire ADD_TC_OP76_n_16, ADD_TC_OP76_n_18, ADD_TC_OP76_n_20,
       ADD_TC_OP76_n_22, ADD_TC_OP76_n_24, ADD_TC_OP76_n_26,
       ADD_TC_OP76_n_28, ADD_TC_OP76_n_30;
  wire ADD_TC_OP76_n_32, ADD_TC_OP78_n_0, ADD_TC_OP78_n_2,
       ADD_TC_OP78_n_4, ADD_TC_OP78_n_6, ADD_TC_OP78_n_8,
       ADD_TC_OP78_n_10, ADD_TC_OP78_n_12;
  wire ADD_TC_OP78_n_14, ADD_TC_OP78_n_16, ADD_TC_OP78_n_18,
       ADD_TC_OP78_n_20, ADD_TC_OP78_n_22, ADD_TC_OP78_n_24,
       ADD_TC_OP78_n_26, ADD_TC_OP78_n_28;
  wire ADD_TC_OP78_n_30, ADD_TC_OP78_n_32, ADD_TC_OP_n_0,
       ADD_TC_OP_n_2, ADD_TC_OP_n_4, ADD_TC_OP_n_6, ADD_TC_OP_n_8,
       ADD_TC_OP_n_10;
  wire ADD_TC_OP_n_12, ADD_TC_OP_n_14, ADD_TC_OP_n_16, ADD_TC_OP_n_18,
       ADD_TC_OP_n_20, ADD_TC_OP_n_22, ADD_TC_OP_n_24, ADD_TC_OP_n_26;
  wire ADD_TC_OP_n_28, ADD_TC_OP_n_30, ADD_TC_OP_n_32, ADD_TC_OP_n_34,
       SUB_TC_OP67_n_0, SUB_TC_OP67_n_1, SUB_TC_OP67_n_2,
       SUB_TC_OP67_n_3;
  wire SUB_TC_OP67_n_4, SUB_TC_OP67_n_5, SUB_TC_OP67_n_6,
       SUB_TC_OP67_n_7, SUB_TC_OP67_n_8, SUB_TC_OP67_n_9,
       SUB_TC_OP67_n_10, SUB_TC_OP67_n_11;
  wire SUB_TC_OP67_n_12, SUB_TC_OP67_n_13, SUB_TC_OP67_n_14,
       SUB_TC_OP67_n_15, SUB_TC_OP67_n_16, SUB_TC_OP67_n_17,
       SUB_TC_OP67_n_18, SUB_TC_OP67_n_19;
  wire SUB_TC_OP67_n_21, SUB_TC_OP67_n_23, SUB_TC_OP67_n_25,
       SUB_TC_OP67_n_27, SUB_TC_OP67_n_29, SUB_TC_OP67_n_31,
       SUB_TC_OP67_n_33, SUB_TC_OP67_n_35;
  wire SUB_TC_OP67_n_37, SUB_TC_OP67_n_39, SUB_TC_OP67_n_41,
       SUB_TC_OP67_n_43, SUB_TC_OP67_n_45, SUB_TC_OP67_n_47,
       SUB_TC_OP67_n_50, SUB_TC_OP67_n_51;
  wire SUB_TC_OP69_n_0, SUB_TC_OP69_n_1, SUB_TC_OP69_n_2,
       SUB_TC_OP69_n_3, SUB_TC_OP69_n_4, SUB_TC_OP69_n_5,
       SUB_TC_OP69_n_6, SUB_TC_OP69_n_7;
  wire SUB_TC_OP69_n_8, SUB_TC_OP69_n_9, SUB_TC_OP69_n_10,
       SUB_TC_OP69_n_11, SUB_TC_OP69_n_12, SUB_TC_OP69_n_13,
       SUB_TC_OP69_n_14, SUB_TC_OP69_n_15;
  wire SUB_TC_OP69_n_16, SUB_TC_OP69_n_17, SUB_TC_OP69_n_18,
       SUB_TC_OP69_n_19, SUB_TC_OP69_n_21, SUB_TC_OP69_n_23,
       SUB_TC_OP69_n_25, SUB_TC_OP69_n_27;
  wire SUB_TC_OP69_n_29, SUB_TC_OP69_n_31, SUB_TC_OP69_n_33,
       SUB_TC_OP69_n_35, SUB_TC_OP69_n_37, SUB_TC_OP69_n_39,
       SUB_TC_OP69_n_41, SUB_TC_OP69_n_43;
  wire SUB_TC_OP69_n_45, SUB_TC_OP69_n_47, SUB_TC_OP69_n_50,
       SUB_TC_OP69_n_51, SUB_TC_OP71_n_0, SUB_TC_OP71_n_1,
       SUB_TC_OP71_n_2, SUB_TC_OP71_n_3;
  wire SUB_TC_OP71_n_4, SUB_TC_OP71_n_5, SUB_TC_OP71_n_6,
       SUB_TC_OP71_n_7, SUB_TC_OP71_n_8, SUB_TC_OP71_n_9,
       SUB_TC_OP71_n_10, SUB_TC_OP71_n_11;
  wire SUB_TC_OP71_n_12, SUB_TC_OP71_n_13, SUB_TC_OP71_n_14,
       SUB_TC_OP71_n_15, SUB_TC_OP71_n_16, SUB_TC_OP71_n_17,
       SUB_TC_OP71_n_18, SUB_TC_OP71_n_19;
  wire SUB_TC_OP71_n_21, SUB_TC_OP71_n_23, SUB_TC_OP71_n_25,
       SUB_TC_OP71_n_27, SUB_TC_OP71_n_29, SUB_TC_OP71_n_31,
       SUB_TC_OP71_n_33, SUB_TC_OP71_n_35;
  wire SUB_TC_OP71_n_37, SUB_TC_OP71_n_39, SUB_TC_OP71_n_41,
       SUB_TC_OP71_n_43, SUB_TC_OP71_n_45, SUB_TC_OP71_n_47,
       SUB_TC_OP71_n_50, SUB_TC_OP71_n_51;
  wire SUB_TC_OP73_n_0, SUB_TC_OP73_n_1, SUB_TC_OP73_n_2,
       SUB_TC_OP73_n_3, SUB_TC_OP73_n_4, SUB_TC_OP73_n_5,
       SUB_TC_OP73_n_6, SUB_TC_OP73_n_7;
  wire SUB_TC_OP73_n_8, SUB_TC_OP73_n_9, SUB_TC_OP73_n_10,
       SUB_TC_OP73_n_11, SUB_TC_OP73_n_12, SUB_TC_OP73_n_13,
       SUB_TC_OP73_n_14, SUB_TC_OP73_n_15;
  wire SUB_TC_OP73_n_16, SUB_TC_OP73_n_17, SUB_TC_OP73_n_18,
       SUB_TC_OP73_n_20, SUB_TC_OP73_n_22, SUB_TC_OP73_n_24,
       SUB_TC_OP73_n_26, SUB_TC_OP73_n_28;
  wire SUB_TC_OP73_n_30, SUB_TC_OP73_n_32, SUB_TC_OP73_n_34,
       SUB_TC_OP73_n_36, SUB_TC_OP73_n_38, SUB_TC_OP73_n_40,
       SUB_TC_OP73_n_42, SUB_TC_OP73_n_44;
  wire SUB_TC_OP73_n_47, SUB_TC_OP73_n_48, SUB_TC_OP75_n_0,
       SUB_TC_OP75_n_1, SUB_TC_OP75_n_2, SUB_TC_OP75_n_3,
       SUB_TC_OP75_n_4, SUB_TC_OP75_n_5;
  wire SUB_TC_OP75_n_6, SUB_TC_OP75_n_7, SUB_TC_OP75_n_8,
       SUB_TC_OP75_n_9, SUB_TC_OP75_n_10, SUB_TC_OP75_n_11,
       SUB_TC_OP75_n_12, SUB_TC_OP75_n_13;
  wire SUB_TC_OP75_n_14, SUB_TC_OP75_n_15, SUB_TC_OP75_n_16,
       SUB_TC_OP75_n_17, SUB_TC_OP75_n_18, SUB_TC_OP75_n_20,
       SUB_TC_OP75_n_22, SUB_TC_OP75_n_24;
  wire SUB_TC_OP75_n_26, SUB_TC_OP75_n_28, SUB_TC_OP75_n_30,
       SUB_TC_OP75_n_32, SUB_TC_OP75_n_34, SUB_TC_OP75_n_36,
       SUB_TC_OP75_n_38, SUB_TC_OP75_n_40;
  wire SUB_TC_OP75_n_42, SUB_TC_OP75_n_44, SUB_TC_OP75_n_47,
       SUB_TC_OP75_n_48, SUB_TC_OP77_n_0, SUB_TC_OP77_n_1,
       SUB_TC_OP77_n_2, SUB_TC_OP77_n_3;
  wire SUB_TC_OP77_n_4, SUB_TC_OP77_n_5, SUB_TC_OP77_n_6,
       SUB_TC_OP77_n_7, SUB_TC_OP77_n_8, SUB_TC_OP77_n_9,
       SUB_TC_OP77_n_10, SUB_TC_OP77_n_11;
  wire SUB_TC_OP77_n_12, SUB_TC_OP77_n_13, SUB_TC_OP77_n_14,
       SUB_TC_OP77_n_15, SUB_TC_OP77_n_16, SUB_TC_OP77_n_17,
       SUB_TC_OP77_n_18, SUB_TC_OP77_n_20;
  wire SUB_TC_OP77_n_22, SUB_TC_OP77_n_24, SUB_TC_OP77_n_26,
       SUB_TC_OP77_n_28, SUB_TC_OP77_n_30, SUB_TC_OP77_n_32,
       SUB_TC_OP77_n_34, SUB_TC_OP77_n_36;
  wire SUB_TC_OP77_n_38, SUB_TC_OP77_n_40, SUB_TC_OP77_n_42,
       SUB_TC_OP77_n_44, SUB_TC_OP77_n_47, SUB_TC_OP77_n_48,
       SUB_TC_OP79_n_0, SUB_TC_OP79_n_1;
  wire SUB_TC_OP79_n_2, SUB_TC_OP79_n_3, SUB_TC_OP79_n_4,
       SUB_TC_OP79_n_5, SUB_TC_OP79_n_6, SUB_TC_OP79_n_7,
       SUB_TC_OP79_n_8, SUB_TC_OP79_n_9;
  wire SUB_TC_OP79_n_10, SUB_TC_OP79_n_11, SUB_TC_OP79_n_12,
       SUB_TC_OP79_n_13, SUB_TC_OP79_n_14, SUB_TC_OP79_n_15,
       SUB_TC_OP79_n_16, SUB_TC_OP79_n_17;
  wire SUB_TC_OP79_n_18, SUB_TC_OP79_n_20, SUB_TC_OP79_n_22,
       SUB_TC_OP79_n_24, SUB_TC_OP79_n_26, SUB_TC_OP79_n_28,
       SUB_TC_OP79_n_30, SUB_TC_OP79_n_32;
  wire SUB_TC_OP79_n_34, SUB_TC_OP79_n_36, SUB_TC_OP79_n_38,
       SUB_TC_OP79_n_40, SUB_TC_OP79_n_42, SUB_TC_OP79_n_44,
       SUB_TC_OP79_n_47, SUB_TC_OP79_n_48;
  wire SUB_TC_OP_n_0, SUB_TC_OP_n_1, SUB_TC_OP_n_2, SUB_TC_OP_n_3,
       SUB_TC_OP_n_4, SUB_TC_OP_n_5, SUB_TC_OP_n_6, SUB_TC_OP_n_7;
  wire SUB_TC_OP_n_8, SUB_TC_OP_n_9, SUB_TC_OP_n_10, SUB_TC_OP_n_11,
       SUB_TC_OP_n_12, SUB_TC_OP_n_13, SUB_TC_OP_n_14, SUB_TC_OP_n_15;
  wire SUB_TC_OP_n_16, SUB_TC_OP_n_17, SUB_TC_OP_n_18, SUB_TC_OP_n_19,
       SUB_TC_OP_n_21, SUB_TC_OP_n_23, SUB_TC_OP_n_25, SUB_TC_OP_n_27;
  wire SUB_TC_OP_n_29, SUB_TC_OP_n_31, SUB_TC_OP_n_33, SUB_TC_OP_n_35,
       SUB_TC_OP_n_37, SUB_TC_OP_n_39, SUB_TC_OP_n_41, SUB_TC_OP_n_43;
  wire SUB_TC_OP_n_45, SUB_TC_OP_n_47, SUB_TC_OP_n_50, SUB_TC_OP_n_51,
       valid_s0, valid_s1;
  DFFRHQX1 \X1_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (X1_r_w[10]),
       .Q (X1_r[10]));
  DFFRHQX1 \X0_r_reg_reg[17] (.RN (rst_n), .CK (clk), .D (X0_r_w[17]),
       .Q (X0_r[17]));
  DFFRHQX1 \X0_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (X0_r_w[15]),
       .Q (X0_r[15]));
  DFFRHQX1 \X0_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (X0_r_w[11]),
       .Q (X0_r[11]));
  DFFRHQX1 \X0_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (X0_r_w[3]), .Q
       (X0_r[3]));
  DFFRHQX1 \X0_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (X0_i_w[5]), .Q
       (X0_i[5]));
  DFFRHQX1 \X1_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (X1_i_w[9]), .Q
       (X1_i[9]));
  DFFRHQX1 \X3_i_reg_reg[17] (.RN (rst_n), .CK (clk), .D (X3_i_w[17]),
       .Q (X3_i[17]));
  DFFRHQX1 \X3_i_reg_reg[16] (.RN (rst_n), .CK (clk), .D (X3_i_w[16]),
       .Q (X3_i[16]));
  DFFRHQX1 \X1_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (X1_i_w[8]), .Q
       (X1_i[8]));
  DFFRHQX1 \X3_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (X3_i_w[15]),
       .Q (X3_i[15]));
  DFFRHQX1 \X3_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (X3_i_w[14]),
       .Q (X3_i[14]));
  DFFRHQX1 \X0_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (X0_i_w[4]), .Q
       (X0_i[4]));
  DFFRHQX1 \X1_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (X1_i_w[7]), .Q
       (X1_i[7]));
  DFFRHQX1 \X3_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (X3_i_w[13]),
       .Q (X3_i[13]));
  DFFRHQX1 \X3_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (X3_i_w[12]),
       .Q (X3_i[12]));
  DFFRHQX1 \X1_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (X1_i_w[6]), .Q
       (X1_i[6]));
  DFFRHQX1 \X3_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (X3_i_w[11]),
       .Q (X3_i[11]));
  DFFRHQX1 \X3_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (X3_i_w[10]),
       .Q (X3_i[10]));
  DFFRHQX1 \X0_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (X0_r_w[2]), .Q
       (X0_r[2]));
  DFFRHQX1 \X0_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (X0_i_w[3]), .Q
       (X0_i[3]));
  DFFRHQX1 \X1_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (X1_i_w[5]), .Q
       (X1_i[5]));
  DFFRHQX1 \X3_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (X3_i_w[9]), .Q
       (X3_i[9]));
  DFFRHQX1 \X3_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (X3_i_w[8]), .Q
       (X3_i[8]));
  DFFRHQX1 \X1_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (X1_i_w[4]), .Q
       (X1_i[4]));
  DFFRHQX1 \X3_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (X3_i_w[7]), .Q
       (X3_i[7]));
  DFFRHQX1 \X3_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (X3_i_w[6]), .Q
       (X3_i[6]));
  DFFRHQX1 \X0_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (X0_i_w[2]), .Q
       (X0_i[2]));
  DFFRHQX1 \X1_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (X1_i_w[3]), .Q
       (X1_i[3]));
  DFFRHQX1 \X3_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (X3_i_w[5]), .Q
       (X3_i[5]));
  DFFRHQX1 \X3_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (X3_i_w[4]), .Q
       (X3_i[4]));
  DFFRHQX1 \X1_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (X1_i_w[2]), .Q
       (X1_i[2]));
  DFFRHQX1 \X3_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (X3_i_w[3]), .Q
       (X3_i[3]));
  DFFRHQX1 \X3_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (X3_i_w[2]), .Q
       (X3_i[2]));
  DFFRHQX1 \X0_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (X0_r_w[10]),
       .Q (X0_r[10]));
  DFFRHQX1 \X0_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (X0_r_w[1]), .Q
       (X0_r[1]));
  DFFRHQX1 \X0_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (X0_i_w[1]), .Q
       (X0_i[1]));
  DFFRHQX1 \X1_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (X1_i_w[1]), .Q
       (X1_i[1]));
  DFFRHQX1 \X3_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (X3_i_w[1]), .Q
       (X3_i[1]));
  DFFRHQX1 \X3_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (X3_i_w[0]), .Q
       (X3_i[0]));
  DFFRHQX1 \X1_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (X1_i_w[0]), .Q
       (X1_i[0]));
  DFFRHQX1 \X0_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (X0_i_w[0]), .Q
       (X0_i[0]));
  DFFRHQX1 \X2_r_reg_reg[17] (.RN (rst_n), .CK (clk), .D (X2_r_w[17]),
       .Q (X2_r[17]));
  DFFRHQX1 \X2_r_reg_reg[16] (.RN (rst_n), .CK (clk), .D (X2_r_w[16]),
       .Q (X2_r[16]));
  DFFRHQX1 \X0_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (X0_r_w[0]), .Q
       (X0_r[0]));
  DFFRHQX1 \X1_r_reg_reg[17] (.RN (rst_n), .CK (clk), .D (X1_r_w[17]),
       .Q (X1_r[17]));
  DFFRHQX1 \X2_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (X2_r_w[15]),
       .Q (X2_r[15]));
  DFFRHQX1 \X2_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (X2_r_w[14]),
       .Q (X2_r[14]));
  DFFRHQX1 \X1_r_reg_reg[16] (.RN (rst_n), .CK (clk), .D (X1_r_w[16]),
       .Q (X1_r[16]));
  DFFRHQX1 \X2_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (X2_r_w[13]),
       .Q (X2_r[13]));
  DFFRHQX1 \X2_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (X2_r_w[12]),
       .Q (X2_r[12]));
  DFFRHQX1 \X0_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (X0_r_w[14]),
       .Q (X0_r[14]));
  DFFRHQX1 \X0_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (X0_r_w[9]), .Q
       (X0_r[9]));
  DFFRHQX1 \X0_i_reg_reg[17] (.RN (rst_n), .CK (clk), .D (X0_i_w[17]),
       .Q (X0_i[17]));
  DFFRHQX1 \X1_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (X1_r_w[15]),
       .Q (X1_r[15]));
  DFFRHQX1 \X2_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (X2_r_w[11]),
       .Q (X2_r[11]));
  DFFRHQX1 \X2_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (X2_r_w[10]),
       .Q (X2_r[10]));
  DFFRHQX1 \X1_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (X1_r_w[14]),
       .Q (X1_r[14]));
  DFFRHQX1 \X2_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (X2_r_w[9]), .Q
       (X2_r[9]));
  DFFRHQX1 \X2_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (X2_r_w[8]), .Q
       (X2_r[8]));
  DFFRHQX1 \X0_i_reg_reg[16] (.RN (rst_n), .CK (clk), .D (X0_i_w[16]),
       .Q (X0_i[16]));
  DFFRHQX1 \X1_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (X1_r_w[13]),
       .Q (X1_r[13]));
  DFFRHQX1 \X2_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (X2_r_w[7]), .Q
       (X2_r[7]));
  DFFRHQX1 \X2_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (X2_r_w[6]), .Q
       (X2_r[6]));
  DFFRHQX1 \X1_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (X1_r_w[12]),
       .Q (X1_r[12]));
  DFFRHQX1 \X2_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (X2_r_w[5]), .Q
       (X2_r[5]));
  DFFRHQX1 \X2_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (X2_r_w[4]), .Q
       (X2_r[4]));
  DFFRHQX1 \X0_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (X0_r_w[8]), .Q
       (X0_r[8]));
  DFFRHQX1 \X0_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (X0_i_w[15]),
       .Q (X0_i[15]));
  DFFRHQX1 \X1_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (X1_r_w[11]),
       .Q (X1_r[11]));
  DFFRHQX1 \X2_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (X2_r_w[3]), .Q
       (X2_r[3]));
  DFFRHQX1 \X2_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (X2_r_w[2]), .Q
       (X2_r[2]));
  DFFRHQX1 \X3_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (X3_r_w[0]), .Q
       (X3_r[0]));
  DFFRHQX1 \X2_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (X2_r_w[0]), .Q
       (X2_r[0]));
  DFFRHQX1 \X0_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (X0_i_w[14]),
       .Q (X0_i[14]));
  DFFRHQX1 \X1_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (X1_r_w[9]), .Q
       (X1_r[9]));
  DFFRHQX1 \X2_i_reg_reg[17] (.RN (rst_n), .CK (clk), .D (X2_i_w[17]),
       .Q (X2_i[17]));
  DFFRHQX1 \X2_i_reg_reg[16] (.RN (rst_n), .CK (clk), .D (X2_i_w[16]),
       .Q (X2_i[16]));
  DFFRHQX1 \X1_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (X1_r_w[8]), .Q
       (X1_r[8]));
  DFFRHQX1 \X2_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (X2_i_w[15]),
       .Q (X2_i[15]));
  DFFRHQX1 \X2_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (X2_i_w[14]),
       .Q (X2_i[14]));
  DFFRHQX1 \X0_r_reg_reg[16] (.RN (rst_n), .CK (clk), .D (X0_r_w[16]),
       .Q (X0_r[16]));
  DFFRHQX1 \X0_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (X0_r_w[13]),
       .Q (X0_r[13]));
  DFFRHQX1 \X0_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (X0_r_w[7]), .Q
       (X0_r[7]));
  DFFRHQX1 \X0_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (X0_i_w[13]),
       .Q (X0_i[13]));
  DFFRHQX1 \X1_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (X1_r_w[7]), .Q
       (X1_r[7]));
  DFFRHQX1 \X2_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (X2_i_w[13]),
       .Q (X2_i[13]));
  DFFRHQX1 \X2_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (X2_i_w[12]),
       .Q (X2_i[12]));
  DFFRHQX1 \X1_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (X1_r_w[6]), .Q
       (X1_r[6]));
  DFFRHQX1 \X2_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (X2_i_w[11]),
       .Q (X2_i[11]));
  DFFRHQX1 \X2_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (X2_i_w[10]),
       .Q (X2_i[10]));
  DFFRHQX1 \X0_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (X0_i_w[12]),
       .Q (X0_i[12]));
  DFFRHQX1 \X1_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (X1_r_w[5]), .Q
       (X1_r[5]));
  DFFRHQX1 \X2_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (X2_i_w[9]), .Q
       (X2_i[9]));
  DFFRHQX1 \X2_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (X2_i_w[8]), .Q
       (X2_i[8]));
  DFFRHQX1 \X1_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (X1_r_w[4]), .Q
       (X1_r[4]));
  DFFRHQX1 \X2_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (X2_i_w[7]), .Q
       (X2_i[7]));
  DFFRHQX1 \X2_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (X2_i_w[6]), .Q
       (X2_i[6]));
  DFFRHQX1 \X0_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (X0_r_w[6]), .Q
       (X0_r[6]));
  DFFRHQX1 \X0_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (X0_i_w[11]),
       .Q (X0_i[11]));
  DFFRHQX1 \X1_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (X1_r_w[3]), .Q
       (X1_r[3]));
  DFFRHQX1 \X2_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (X2_i_w[5]), .Q
       (X2_i[5]));
  DFFRHQX1 \X2_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (X2_i_w[4]), .Q
       (X2_i[4]));
  DFFRHQX1 \X1_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (X1_r_w[2]), .Q
       (X1_r[2]));
  DFFRHQX1 \X2_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (X2_i_w[3]), .Q
       (X2_i[3]));
  DFFRHQX1 \X2_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (X2_i_w[2]), .Q
       (X2_i[2]));
  DFFRHQX1 \X0_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (X0_i_w[10]),
       .Q (X0_i[10]));
  DFFRHQX1 \X1_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (X1_r_w[1]), .Q
       (X1_r[1]));
  DFFRHQX1 \X2_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (X2_i_w[1]), .Q
       (X2_i[1]));
  DFFRHQX1 \X2_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (X2_i_w[0]), .Q
       (X2_i[0]));
  DFFRHQX1 \X1_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (X1_r_w[0]), .Q
       (X1_r[0]));
  DFFRHQX1 \X3_r_reg_reg[17] (.RN (rst_n), .CK (clk), .D (X3_r_w[17]),
       .Q (X3_r[17]));
  DFFRHQX1 \X3_r_reg_reg[16] (.RN (rst_n), .CK (clk), .D (X3_r_w[16]),
       .Q (X3_r[16]));
  DFFRHQX1 \X0_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (X0_r_w[12]),
       .Q (X0_r[12]));
  DFFRHQX1 \X0_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (X0_r_w[5]), .Q
       (X0_r[5]));
  DFFRHQX1 \X0_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (X0_i_w[9]), .Q
       (X0_i[9]));
  DFFRHQX1 \X1_i_reg_reg[17] (.RN (rst_n), .CK (clk), .D (X1_i_w[17]),
       .Q (X1_i[17]));
  DFFRHQX1 \X3_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (X3_r_w[15]),
       .Q (X3_r[15]));
  DFFRHQX1 \X3_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (X3_r_w[14]),
       .Q (X3_r[14]));
  DFFRHQX1 \X1_i_reg_reg[16] (.RN (rst_n), .CK (clk), .D (X1_i_w[16]),
       .Q (X1_i[16]));
  DFFRHQX1 \X3_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (X3_r_w[13]),
       .Q (X3_r[13]));
  DFFRHQX1 \X3_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (X3_r_w[12]),
       .Q (X3_r[12]));
  DFFRHQX1 \X0_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (X0_i_w[8]), .Q
       (X0_i[8]));
  DFFRHQX1 \X1_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (X1_i_w[15]),
       .Q (X1_i[15]));
  DFFRHQX1 \X3_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (X3_r_w[11]),
       .Q (X3_r[11]));
  DFFRHQX1 \X3_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (X3_r_w[10]),
       .Q (X3_r[10]));
  DFFRHQX1 \X1_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (X1_i_w[14]),
       .Q (X1_i[14]));
  DFFRHQX1 \X3_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (X3_r_w[9]), .Q
       (X3_r[9]));
  DFFRHQX1 \X3_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (X3_r_w[8]), .Q
       (X3_r[8]));
  DFFRHQX1 \X0_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (X0_r_w[4]), .Q
       (X0_r[4]));
  DFFRHQX1 \X0_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (X0_i_w[7]), .Q
       (X0_i[7]));
  DFFRHQX1 \X1_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (X1_i_w[13]),
       .Q (X1_i[13]));
  DFFRHQX1 \X3_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (X3_r_w[7]), .Q
       (X3_r[7]));
  DFFRHQX1 \X3_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (X3_r_w[6]), .Q
       (X3_r[6]));
  DFFRHQX1 \X1_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (X1_i_w[12]),
       .Q (X1_i[12]));
  DFFRHQX1 \X3_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (X3_r_w[5]), .Q
       (X3_r[5]));
  DFFRHQX1 \X3_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (X3_r_w[4]), .Q
       (X3_r[4]));
  DFFRHQX1 \X0_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (X0_i_w[6]), .Q
       (X0_i[6]));
  DFFRHQX1 \X1_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (X1_i_w[11]),
       .Q (X1_i[11]));
  DFFRHQX1 \X3_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (X3_r_w[3]), .Q
       (X3_r[3]));
  DFFRHQX1 \X3_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (X3_r_w[2]), .Q
       (X3_r[2]));
  DFFRHQX1 \X1_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (X1_i_w[10]),
       .Q (X1_i[10]));
  DFFRHQX1 \X3_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (X3_r_w[1]), .Q
       (X3_r[1]));
  DFFRHQX1 \X2_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (X2_r_w[1]), .Q
       (X2_r[1]));
  DFFRHQX1 \B_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (B_i[8]), .Q
       (B_i_reg[8]));
  DFFRHQX1 \B_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (B_i[3]), .Q
       (B_i_reg[3]));
  DFFRHQX1 \A_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (A_i[4]), .Q
       (A_i_reg[4]));
  DFFRHQX1 \B_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (B_i[13]), .Q
       (B_i_reg[13]));
  DFFRHQX1 \C_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (C_r[0]), .Q
       (C_r_reg[0]));
  DFFRHQX1 \A_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (A_i[6]), .Q
       (A_i_reg[6]));
  DFFRHQX1 \A_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (A_i[9]), .Q
       (A_i_reg[9]));
  DFFRHQX1 \A_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (A_i[14]), .Q
       (A_i_reg[14]));
  DFFRHQX1 \A_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (A_i[11]), .Q
       (A_i_reg[11]));
  DFFRHQX1 \A_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (A_r[11]), .Q
       (A_r_reg[11]));
  DFFRHQX1 \A_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (A_r[6]), .Q
       (A_r_reg[6]));
  DFFRHQX1 \A_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (A_r[7]), .Q
       (A_r_reg[7]));
  DFFRHQX1 \D_i_reg_reg[16] (.RN (rst_n), .CK (clk), .D (D_i[16]), .Q
       (D_i_reg[16]));
  DFFRHQX1 \A_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (A_r[1]), .Q
       (A_r_reg[1]));
  DFFRHQX1 \B_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (B_r[8]), .Q
       (B_r_reg[8]));
  DFFRHQX1 \B_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (B_r[5]), .Q
       (B_r_reg[5]));
  DFFRHQX1 \B_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (B_r[11]), .Q
       (B_r_reg[11]));
  DFFRHQX1 \B_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (B_r[14]), .Q
       (B_r_reg[14]));
  DFFRHQX1 \D_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (D_r[0]), .Q
       (D_r_reg[0]));
  DFFRHQX1 \B_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (B_r[2]), .Q
       (B_r_reg[2]));
  DFFRHQX1 \B_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (B_r[15]), .Q
       (B_r_reg[15]));
  DFFRHQX1 \B_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (B_r[13]), .Q
       (B_r_reg[13]));
  DFFRHQX1 \B_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (B_r[12]), .Q
       (B_r_reg[12]));
  DFFRHQX1 \B_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (B_r[10]), .Q
       (B_r_reg[10]));
  DFFRHQX1 \B_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (B_r[9]), .Q
       (B_r_reg[9]));
  DFFRHQX1 \C_r_reg_reg[16] (.RN (rst_n), .CK (clk), .D (C_r[16]), .Q
       (C_r_reg[16]));
  DFFRHQX1 \B_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (B_r[7]), .Q
       (B_r_reg[7]));
  DFFRHQX1 \B_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (B_r[6]), .Q
       (B_r_reg[6]));
  DFFRHQX1 \B_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (B_r[4]), .Q
       (B_r_reg[4]));
  DFFRHQX1 \A_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (A_r[2]), .Q
       (A_r_reg[2]));
  DFFRHQX1 \B_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (B_r[3]), .Q
       (B_r_reg[3]));
  DFFRHQX1 \A_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (A_r[3]), .Q
       (A_r_reg[3]));
  DFFRHQX1 \B_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (B_r[1]), .Q
       (B_r_reg[1]));
  DFFRHQX1 \A_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (A_r[5]), .Q
       (A_r_reg[5]));
  DFFRHQX1 \A_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (A_r[4]), .Q
       (A_r_reg[4]));
  DFFRHQX1 \B_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (B_i[6]), .Q
       (B_i_reg[6]));
  DFFRHQX1 \A_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (A_r[9]), .Q
       (A_r_reg[9]));
  DFFRHQX1 \D_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (D_i[0]), .Q
       (D_i_reg[0]));
  DFFRHQX1 \A_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (A_r[8]), .Q
       (A_r_reg[8]));
  DFFRHQX1 \A_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (A_r[10]), .Q
       (A_r_reg[10]));
  DFFRHQX1 \A_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (A_r[13]), .Q
       (A_r_reg[13]));
  DFFRHQX1 \A_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (A_i[15]), .Q
       (A_i_reg[15]));
  DFFRHQX1 \A_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (A_r[12]), .Q
       (A_r_reg[12]));
  DFFRHQX1 \A_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (A_i[13]), .Q
       (A_i_reg[13]));
  DFFRHQX1 \A_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (A_i[12]), .Q
       (A_i_reg[12]));
  DFFRHQX1 \A_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (A_r[15]), .Q
       (A_r_reg[15]));
  DFFRHQX1 \A_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (A_i[8]), .Q
       (A_i_reg[8]));
  DFFRHQX1 \A_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (A_i[7]), .Q
       (A_i_reg[7]));
  DFFRHQX1 \A_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (A_r[14]), .Q
       (A_r_reg[14]));
  DFFRHQX1 \A_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (A_i[5]), .Q
       (A_i_reg[5]));
  DFFRHQX1 \A_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (A_i[3]), .Q
       (A_i_reg[3]));
  DFFRHQX1 \A_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (A_i[2]), .Q
       (A_i_reg[2]));
  DFFRHQX1 \A_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (A_i[1]), .Q
       (A_i_reg[1]));
  DFFRHQX1 \C_i_reg_reg[16] (.RN (rst_n), .CK (clk), .D (C_i[16]), .Q
       (C_i_reg[16]));
  DFFRHQX1 \B_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (B_i[2]), .Q
       (B_i_reg[2]));
  DFFRHQX1 \B_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (B_i[10]), .Q
       (B_i_reg[10]));
  DFFRHQX1 \A_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (A_i[10]), .Q
       (A_i_reg[10]));
  DFFRHQX1 \C_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (C_i[0]), .Q
       (C_i_reg[0]));
  DFFRHQX1 \B_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (B_i[15]), .Q
       (B_i_reg[15]));
  DFFRHQX1 \B_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (B_i[14]), .Q
       (B_i_reg[14]));
  DFFRHQX1 \B_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (B_i[12]), .Q
       (B_i_reg[12]));
  DFFRHQX1 \B_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (B_i[11]), .Q
       (B_i_reg[11]));
  DFFRHQX1 \B_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (B_i[9]), .Q
       (B_i_reg[9]));
  DFFRHQX1 \B_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (B_i[7]), .Q
       (B_i_reg[7]));
  DFFRHQX1 \B_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (B_i[5]), .Q
       (B_i_reg[5]));
  DFFRHQX1 \B_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (B_i[4]), .Q
       (B_i_reg[4]));
  DFFRHQX1 \B_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (B_i[1]), .Q
       (B_i_reg[1]));
  DFFRHQX1 \D_r_reg_reg[16] (.RN (rst_n), .CK (clk), .D (D_r[16]), .Q
       (D_r_reg[16]));
  DFFRHQX1 valid_s2_reg(.RN (rst_n), .CK (clk), .D (valid_s1), .Q
       (data_valid_out));
  DFFRHQX1 valid_s1_reg(.RN (rst_n), .CK (clk), .D (valid_s0), .Q
       (valid_s1));
  DFFRHQX1 valid_s0_reg(.RN (rst_n), .CK (clk), .D (data_valid_in), .Q
       (valid_s0));
  DFFRHQX1 \x1_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (x1_i[4]), .Q
       (x1_i_reg[4]));
  DFFRHQX1 \x1_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (x1_r[8]), .Q
       (x1_r_reg[8]));
  DFFRHQX1 \x1_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (x1_r[12]), .Q
       (x1_r_reg[12]));
  DFFRHQX1 \x1_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (x1_r[7]), .Q
       (x1_r_reg[7]));
  DFFRHQX1 \x1_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (x1_i[2]), .Q
       (x1_i_reg[2]));
  DFFRHQX1 \x1_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (x1_i[8]), .Q
       (x1_i_reg[8]));
  DFFRHQX1 \x1_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (x1_r[6]), .Q
       (x1_r_reg[6]));
  DFFRHQX1 \x3_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (x3_r[15]), .Q
       (x3_r_reg[15]));
  DFFRHQX1 \x0_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (x0_i[12]), .Q
       (x0_i_reg[12]));
  DFFRHQX1 \x0_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (x0_i[13]), .Q
       (x0_i_reg[13]));
  DFFRHQX1 \x1_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (x1_r[14]), .Q
       (x1_r_reg[14]));
  DFFRHQX1 \x0_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (x0_i[10]), .Q
       (x0_i_reg[10]));
  DFFRHQX1 \x0_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (x0_i[7]), .Q
       (x0_i_reg[7]));
  DFFRHQX1 \x0_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (x0_i[5]), .Q
       (x0_i_reg[5]));
  DFFRHQX1 \x0_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (x0_r[8]), .Q
       (x0_r_reg[8]));
  DFFRHQX1 \x0_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (x0_r[2]), .Q
       (x0_r_reg[2]));
  DFFRHQX1 \x1_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (x1_i[12]), .Q
       (x1_i_reg[12]));
  DFFRHQX1 \x2_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (x2_i[0]), .Q
       (x2_i_reg[0]));
  DFFRHQX1 \x0_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (x0_r[11]), .Q
       (x0_r_reg[11]));
  DFFRHQX1 \x0_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (x0_r[5]), .Q
       (x0_r_reg[5]));
  DFFRHQX1 \x0_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (x0_i[1]), .Q
       (x0_i_reg[1]));
  DFFRHQX1 \x0_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (x0_r[6]), .Q
       (x0_r_reg[6]));
  DFFRHQX1 \x1_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (x1_i[3]), .Q
       (x1_i_reg[3]));
  DFFRHQX1 \x0_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (x0_r[4]), .Q
       (x0_r_reg[4]));
  DFFRHQX1 \x1_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (x1_i[13]), .Q
       (x1_i_reg[13]));
  DFFRHQX1 \x0_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (x0_i[2]), .Q
       (x0_i_reg[2]));
  DFFRHQX1 \x1_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (x1_r[4]), .Q
       (x1_r_reg[4]));
  DFFRHQX1 \x0_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (x0_r[13]), .Q
       (x0_r_reg[13]));
  DFFRHQX1 \x0_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (x0_r[12]), .Q
       (x0_r_reg[12]));
  DFFRHQX1 \x1_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (x1_r[1]), .Q
       (x1_r_reg[1]));
  DFFRHQX1 \x1_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (x1_r[9]), .Q
       (x1_r_reg[9]));
  DFFRHQX1 \x1_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (x1_r[13]), .Q
       (x1_r_reg[13]));
  DFFRHQX1 \x1_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (x1_i[7]), .Q
       (x1_i_reg[7]));
  DFFRHQX1 \x3_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (x3_i[15]), .Q
       (x3_i_reg[15]));
  DFFRHQX1 \x3_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (x3_i[0]), .Q
       (x3_i_reg[0]));
  DFFRHQX1 \x2_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (x2_i[15]), .Q
       (x2_i_reg[15]));
  DFFRHQX1 \x1_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (x1_i[6]), .Q
       (x1_i_reg[6]));
  DFFRHQX1 \x1_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (x1_i[10]), .Q
       (x1_i_reg[10]));
  DFFRHQX1 \x1_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (x1_i[14]), .Q
       (x1_i_reg[14]));
  DFFRHQX1 \x1_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (x1_r[11]), .Q
       (x1_r_reg[11]));
  DFFRHQX1 \x1_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (x1_r[5]), .Q
       (x1_r_reg[5]));
  DFFRHQX1 \x1_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (x1_r[3]), .Q
       (x1_r_reg[3]));
  DFFRHQX1 \x0_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (x0_r[14]), .Q
       (x0_r_reg[14]));
  DFFRHQX1 \x0_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (x0_i[14]), .Q
       (x0_i_reg[14]));
  DFFRHQX1 \x1_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (x1_i[9]), .Q
       (x1_i_reg[9]));
  DFFRHQX1 \x0_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (x0_i[6]), .Q
       (x0_i_reg[6]));
  DFFRHQX1 \x1_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (x1_i[5]), .Q
       (x1_i_reg[5]));
  DFFRHQX1 \x3_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (x3_r[0]), .Q
       (x3_r_reg[0]));
  DFFRHQX1 \x2_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (x2_r[0]), .Q
       (x2_r_reg[0]));
  DFFRHQX1 \x0_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (x0_r[7]), .Q
       (x0_r_reg[7]));
  DFFRHQX1 \x0_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (x0_i[8]), .Q
       (x0_i_reg[8]));
  DFFRHQX1 \x0_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (x0_i[3]), .Q
       (x0_i_reg[3]));
  DFFRHQX1 \x0_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (x0_i[11]), .Q
       (x0_i_reg[11]));
  DFFRHQX1 \x0_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (x0_r[10]), .Q
       (x0_r_reg[10]));
  DFFRHQX1 \x0_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (x0_r[1]), .Q
       (x0_r_reg[1]));
  DFFRHQX1 \x2_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (x2_r[15]), .Q
       (x2_r_reg[15]));
  DFFRHQX1 \x0_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (x0_r[9]), .Q
       (x0_r_reg[9]));
  DFFRHQX1 \x1_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (x1_i[1]), .Q
       (x1_i_reg[1]));
  DFFRHQX1 \x1_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (x1_i[11]), .Q
       (x1_i_reg[11]));
  DFFRHQX1 \x0_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (x0_r[3]), .Q
       (x0_r_reg[3]));
  DFFRHQX1 \x0_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (x0_i[4]), .Q
       (x0_i_reg[4]));
  DFFRHQX1 \x0_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (x0_i[9]), .Q
       (x0_i_reg[9]));
  DFFRHQX1 \x1_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (x1_r[2]), .Q
       (x1_r_reg[2]));
  DFFRHQX1 \x1_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (x1_r[10]), .Q
       (x1_r_reg[10]));
  INVXL ADD_TC_OP_g410(.A (ADD_TC_OP_n_34), .Y (X1_r_w[16]));
  ADDFXL ADD_TC_OP_g411__2398(.A (B_r_reg[16]), .B (D_i_reg[16]), .CI
       (ADD_TC_OP_n_32), .CO (X1_r_w[17]), .S (ADD_TC_OP_n_34));
  INVX1 ADD_TC_OP_g412(.A (ADD_TC_OP_n_30), .Y (ADD_TC_OP_n_32));
  ADDFXL ADD_TC_OP_g413__5107(.A (B_r_reg[15]), .B (D_i_reg[15]), .CI
       (ADD_TC_OP_n_28), .CO (ADD_TC_OP_n_30), .S (X1_r_w[15]));
  ADDFX1 ADD_TC_OP_g414__6260(.A (D_i_reg[14]), .B (B_r_reg[14]), .CI
       (ADD_TC_OP_n_26), .CO (ADD_TC_OP_n_28), .S (X1_r_w[14]));
  ADDFX1 ADD_TC_OP_g415__4319(.A (D_i_reg[13]), .B (B_r_reg[13]), .CI
       (ADD_TC_OP_n_24), .CO (ADD_TC_OP_n_26), .S (X1_r_w[13]));
  ADDFX1 ADD_TC_OP_g416__8428(.A (D_i_reg[12]), .B (B_r_reg[12]), .CI
       (ADD_TC_OP_n_22), .CO (ADD_TC_OP_n_24), .S (X1_r_w[12]));
  ADDFX1 ADD_TC_OP_g417__5526(.A (D_i_reg[11]), .B (B_r_reg[11]), .CI
       (ADD_TC_OP_n_20), .CO (ADD_TC_OP_n_22), .S (X1_r_w[11]));
  ADDFX1 ADD_TC_OP_g418__6783(.A (D_i_reg[10]), .B (B_r_reg[10]), .CI
       (ADD_TC_OP_n_18), .CO (ADD_TC_OP_n_20), .S (X1_r_w[10]));
  ADDFX1 ADD_TC_OP_g419__3680(.A (D_i_reg[9]), .B (B_r_reg[9]), .CI
       (ADD_TC_OP_n_16), .CO (ADD_TC_OP_n_18), .S (X1_r_w[9]));
  ADDFX1 ADD_TC_OP_g420__1617(.A (D_i_reg[8]), .B (B_r_reg[8]), .CI
       (ADD_TC_OP_n_14), .CO (ADD_TC_OP_n_16), .S (X1_r_w[8]));
  ADDFX1 ADD_TC_OP_g421__2802(.A (D_i_reg[7]), .B (B_r_reg[7]), .CI
       (ADD_TC_OP_n_12), .CO (ADD_TC_OP_n_14), .S (X1_r_w[7]));
  ADDFX1 ADD_TC_OP_g422__1705(.A (D_i_reg[6]), .B (B_r_reg[6]), .CI
       (ADD_TC_OP_n_10), .CO (ADD_TC_OP_n_12), .S (X1_r_w[6]));
  ADDFX1 ADD_TC_OP_g423__5122(.A (D_i_reg[5]), .B (B_r_reg[5]), .CI
       (ADD_TC_OP_n_8), .CO (ADD_TC_OP_n_10), .S (X1_r_w[5]));
  ADDFX1 ADD_TC_OP_g424__8246(.A (D_i_reg[4]), .B (B_r_reg[4]), .CI
       (ADD_TC_OP_n_6), .CO (ADD_TC_OP_n_8), .S (X1_r_w[4]));
  ADDFX1 ADD_TC_OP_g425__7098(.A (D_i_reg[3]), .B (B_r_reg[3]), .CI
       (ADD_TC_OP_n_4), .CO (ADD_TC_OP_n_6), .S (X1_r_w[3]));
  ADDFX1 ADD_TC_OP_g426__6131(.A (D_i_reg[2]), .B (B_r_reg[2]), .CI
       (ADD_TC_OP_n_2), .CO (ADD_TC_OP_n_4), .S (X1_r_w[2]));
  ADDFX1 ADD_TC_OP_g427__1881(.A (D_i_reg[1]), .B (B_r_reg[1]), .CI
       (ADD_TC_OP_n_0), .CO (ADD_TC_OP_n_2), .S (X1_r_w[1]));
  AOI2BB1X1 ADD_TC_OP_g428__5115(.A0N (B_r_reg[0]), .A1N (D_i_reg[0]),
       .B0 (ADD_TC_OP_n_0), .Y (X1_r_w[0]));
  AND2X1 ADD_TC_OP_g429__7482(.A (D_i_reg[0]), .B (B_r_reg[0]), .Y
       (ADD_TC_OP_n_0));
  INVXL ADD_TC_OP66_g410(.A (ADD_TC_OP66_n_34), .Y (X0_i_w[16]));
  ADDFXL ADD_TC_OP66_g411__4733(.A (A_i_reg[16]), .B (C_i_reg[16]), .CI
       (ADD_TC_OP66_n_32), .CO (X0_i_w[17]), .S (ADD_TC_OP66_n_34));
  INVX1 ADD_TC_OP66_g412(.A (ADD_TC_OP66_n_30), .Y (ADD_TC_OP66_n_32));
  ADDFXL ADD_TC_OP66_g413__6161(.A (A_i_reg[15]), .B (C_i_reg[15]), .CI
       (ADD_TC_OP66_n_28), .CO (ADD_TC_OP66_n_30), .S (X0_i_w[15]));
  ADDFX1 ADD_TC_OP66_g414__9315(.A (C_i_reg[14]), .B (A_i_reg[14]), .CI
       (ADD_TC_OP66_n_26), .CO (ADD_TC_OP66_n_28), .S (X0_i_w[14]));
  ADDFX1 ADD_TC_OP66_g415__9945(.A (C_i_reg[13]), .B (A_i_reg[13]), .CI
       (ADD_TC_OP66_n_24), .CO (ADD_TC_OP66_n_26), .S (X0_i_w[13]));
  ADDFX1 ADD_TC_OP66_g416__2883(.A (C_i_reg[12]), .B (A_i_reg[12]), .CI
       (ADD_TC_OP66_n_22), .CO (ADD_TC_OP66_n_24), .S (X0_i_w[12]));
  ADDFX1 ADD_TC_OP66_g417__2346(.A (C_i_reg[11]), .B (A_i_reg[11]), .CI
       (ADD_TC_OP66_n_20), .CO (ADD_TC_OP66_n_22), .S (X0_i_w[11]));
  ADDFX1 ADD_TC_OP66_g418__1666(.A (C_i_reg[10]), .B (A_i_reg[10]), .CI
       (ADD_TC_OP66_n_18), .CO (ADD_TC_OP66_n_20), .S (X0_i_w[10]));
  ADDFX1 ADD_TC_OP66_g419__7410(.A (C_i_reg[9]), .B (A_i_reg[9]), .CI
       (ADD_TC_OP66_n_16), .CO (ADD_TC_OP66_n_18), .S (X0_i_w[9]));
  ADDFX1 ADD_TC_OP66_g420__6417(.A (C_i_reg[8]), .B (A_i_reg[8]), .CI
       (ADD_TC_OP66_n_14), .CO (ADD_TC_OP66_n_16), .S (X0_i_w[8]));
  ADDFX1 ADD_TC_OP66_g421__5477(.A (C_i_reg[7]), .B (A_i_reg[7]), .CI
       (ADD_TC_OP66_n_12), .CO (ADD_TC_OP66_n_14), .S (X0_i_w[7]));
  ADDFX1 ADD_TC_OP66_g422__2398(.A (C_i_reg[6]), .B (A_i_reg[6]), .CI
       (ADD_TC_OP66_n_10), .CO (ADD_TC_OP66_n_12), .S (X0_i_w[6]));
  ADDFX1 ADD_TC_OP66_g423__5107(.A (C_i_reg[5]), .B (A_i_reg[5]), .CI
       (ADD_TC_OP66_n_8), .CO (ADD_TC_OP66_n_10), .S (X0_i_w[5]));
  ADDFX1 ADD_TC_OP66_g424__6260(.A (C_i_reg[4]), .B (A_i_reg[4]), .CI
       (ADD_TC_OP66_n_6), .CO (ADD_TC_OP66_n_8), .S (X0_i_w[4]));
  ADDFX1 ADD_TC_OP66_g425__4319(.A (C_i_reg[3]), .B (A_i_reg[3]), .CI
       (ADD_TC_OP66_n_4), .CO (ADD_TC_OP66_n_6), .S (X0_i_w[3]));
  ADDFX1 ADD_TC_OP66_g426__8428(.A (C_i_reg[2]), .B (A_i_reg[2]), .CI
       (ADD_TC_OP66_n_2), .CO (ADD_TC_OP66_n_4), .S (X0_i_w[2]));
  ADDFX1 ADD_TC_OP66_g427__5526(.A (C_i_reg[1]), .B (A_i_reg[1]), .CI
       (ADD_TC_OP66_n_0), .CO (ADD_TC_OP66_n_2), .S (X0_i_w[1]));
  AOI2BB1X1 ADD_TC_OP66_g428__6783(.A0N (A_i_reg[0]), .A1N
       (C_i_reg[0]), .B0 (ADD_TC_OP66_n_0), .Y (X0_i_w[0]));
  AND2X1 ADD_TC_OP66_g429__3680(.A (C_i_reg[0]), .B (A_i_reg[0]), .Y
       (ADD_TC_OP66_n_0));
  INVXL ADD_TC_OP68_g410(.A (ADD_TC_OP68_n_34), .Y (X0_r_w[16]));
  ADDFXL ADD_TC_OP68_g411__1617(.A (A_r_reg[16]), .B (C_r_reg[16]), .CI
       (ADD_TC_OP68_n_32), .CO (X0_r_w[17]), .S (ADD_TC_OP68_n_34));
  INVX1 ADD_TC_OP68_g412(.A (ADD_TC_OP68_n_30), .Y (ADD_TC_OP68_n_32));
  ADDFXL ADD_TC_OP68_g413__2802(.A (A_r_reg[15]), .B (C_r_reg[15]), .CI
       (ADD_TC_OP68_n_28), .CO (ADD_TC_OP68_n_30), .S (X0_r_w[15]));
  ADDFX1 ADD_TC_OP68_g414__1705(.A (C_r_reg[14]), .B (A_r_reg[14]), .CI
       (ADD_TC_OP68_n_26), .CO (ADD_TC_OP68_n_28), .S (X0_r_w[14]));
  ADDFX1 ADD_TC_OP68_g415__5122(.A (C_r_reg[13]), .B (A_r_reg[13]), .CI
       (ADD_TC_OP68_n_24), .CO (ADD_TC_OP68_n_26), .S (X0_r_w[13]));
  ADDFX1 ADD_TC_OP68_g416__8246(.A (C_r_reg[12]), .B (A_r_reg[12]), .CI
       (ADD_TC_OP68_n_22), .CO (ADD_TC_OP68_n_24), .S (X0_r_w[12]));
  ADDFX1 ADD_TC_OP68_g417__7098(.A (C_r_reg[11]), .B (A_r_reg[11]), .CI
       (ADD_TC_OP68_n_20), .CO (ADD_TC_OP68_n_22), .S (X0_r_w[11]));
  ADDFX1 ADD_TC_OP68_g418__6131(.A (C_r_reg[10]), .B (A_r_reg[10]), .CI
       (ADD_TC_OP68_n_18), .CO (ADD_TC_OP68_n_20), .S (X0_r_w[10]));
  ADDFX1 ADD_TC_OP68_g419__1881(.A (C_r_reg[9]), .B (A_r_reg[9]), .CI
       (ADD_TC_OP68_n_16), .CO (ADD_TC_OP68_n_18), .S (X0_r_w[9]));
  ADDFX1 ADD_TC_OP68_g420__5115(.A (C_r_reg[8]), .B (A_r_reg[8]), .CI
       (ADD_TC_OP68_n_14), .CO (ADD_TC_OP68_n_16), .S (X0_r_w[8]));
  ADDFX1 ADD_TC_OP68_g421__7482(.A (C_r_reg[7]), .B (A_r_reg[7]), .CI
       (ADD_TC_OP68_n_12), .CO (ADD_TC_OP68_n_14), .S (X0_r_w[7]));
  ADDFX1 ADD_TC_OP68_g422__4733(.A (C_r_reg[6]), .B (A_r_reg[6]), .CI
       (ADD_TC_OP68_n_10), .CO (ADD_TC_OP68_n_12), .S (X0_r_w[6]));
  ADDFX1 ADD_TC_OP68_g423__6161(.A (C_r_reg[5]), .B (A_r_reg[5]), .CI
       (ADD_TC_OP68_n_8), .CO (ADD_TC_OP68_n_10), .S (X0_r_w[5]));
  ADDFX1 ADD_TC_OP68_g424__9315(.A (C_r_reg[4]), .B (A_r_reg[4]), .CI
       (ADD_TC_OP68_n_6), .CO (ADD_TC_OP68_n_8), .S (X0_r_w[4]));
  ADDFX1 ADD_TC_OP68_g425__9945(.A (C_r_reg[3]), .B (A_r_reg[3]), .CI
       (ADD_TC_OP68_n_4), .CO (ADD_TC_OP68_n_6), .S (X0_r_w[3]));
  ADDFX1 ADD_TC_OP68_g426__2883(.A (C_r_reg[2]), .B (A_r_reg[2]), .CI
       (ADD_TC_OP68_n_2), .CO (ADD_TC_OP68_n_4), .S (X0_r_w[2]));
  ADDFX1 ADD_TC_OP68_g427__2346(.A (C_r_reg[1]), .B (A_r_reg[1]), .CI
       (ADD_TC_OP68_n_0), .CO (ADD_TC_OP68_n_2), .S (X0_r_w[1]));
  AOI2BB1X1 ADD_TC_OP68_g428__1666(.A0N (A_r_reg[0]), .A1N
       (C_r_reg[0]), .B0 (ADD_TC_OP68_n_0), .Y (X0_r_w[0]));
  AND2X1 ADD_TC_OP68_g429__7410(.A (C_r_reg[0]), .B (A_r_reg[0]), .Y
       (ADD_TC_OP68_n_0));
  INVXL ADD_TC_OP70_g410(.A (ADD_TC_OP70_n_34), .Y (X3_i_w[16]));
  ADDFXL ADD_TC_OP70_g411__6417(.A (B_i_reg[16]), .B (D_r_reg[16]), .CI
       (ADD_TC_OP70_n_32), .CO (X3_i_w[17]), .S (ADD_TC_OP70_n_34));
  INVX1 ADD_TC_OP70_g412(.A (ADD_TC_OP70_n_30), .Y (ADD_TC_OP70_n_32));
  ADDFXL ADD_TC_OP70_g413__5477(.A (B_i_reg[15]), .B (D_r_reg[15]), .CI
       (ADD_TC_OP70_n_28), .CO (ADD_TC_OP70_n_30), .S (X3_i_w[15]));
  ADDFX1 ADD_TC_OP70_g414__2398(.A (D_r_reg[14]), .B (B_i_reg[14]), .CI
       (ADD_TC_OP70_n_26), .CO (ADD_TC_OP70_n_28), .S (X3_i_w[14]));
  ADDFX1 ADD_TC_OP70_g415__5107(.A (D_r_reg[13]), .B (B_i_reg[13]), .CI
       (ADD_TC_OP70_n_24), .CO (ADD_TC_OP70_n_26), .S (X3_i_w[13]));
  ADDFX1 ADD_TC_OP70_g416__6260(.A (D_r_reg[12]), .B (B_i_reg[12]), .CI
       (ADD_TC_OP70_n_22), .CO (ADD_TC_OP70_n_24), .S (X3_i_w[12]));
  ADDFX1 ADD_TC_OP70_g417__4319(.A (D_r_reg[11]), .B (B_i_reg[11]), .CI
       (ADD_TC_OP70_n_20), .CO (ADD_TC_OP70_n_22), .S (X3_i_w[11]));
  ADDFX1 ADD_TC_OP70_g418__8428(.A (D_r_reg[10]), .B (B_i_reg[10]), .CI
       (ADD_TC_OP70_n_18), .CO (ADD_TC_OP70_n_20), .S (X3_i_w[10]));
  ADDFX1 ADD_TC_OP70_g419__5526(.A (D_r_reg[9]), .B (B_i_reg[9]), .CI
       (ADD_TC_OP70_n_16), .CO (ADD_TC_OP70_n_18), .S (X3_i_w[9]));
  ADDFX1 ADD_TC_OP70_g420__6783(.A (D_r_reg[8]), .B (B_i_reg[8]), .CI
       (ADD_TC_OP70_n_14), .CO (ADD_TC_OP70_n_16), .S (X3_i_w[8]));
  ADDFX1 ADD_TC_OP70_g421__3680(.A (D_r_reg[7]), .B (B_i_reg[7]), .CI
       (ADD_TC_OP70_n_12), .CO (ADD_TC_OP70_n_14), .S (X3_i_w[7]));
  ADDFX1 ADD_TC_OP70_g422__1617(.A (D_r_reg[6]), .B (B_i_reg[6]), .CI
       (ADD_TC_OP70_n_10), .CO (ADD_TC_OP70_n_12), .S (X3_i_w[6]));
  ADDFX1 ADD_TC_OP70_g423__2802(.A (D_r_reg[5]), .B (B_i_reg[5]), .CI
       (ADD_TC_OP70_n_8), .CO (ADD_TC_OP70_n_10), .S (X3_i_w[5]));
  ADDFX1 ADD_TC_OP70_g424__1705(.A (D_r_reg[4]), .B (B_i_reg[4]), .CI
       (ADD_TC_OP70_n_6), .CO (ADD_TC_OP70_n_8), .S (X3_i_w[4]));
  ADDFX1 ADD_TC_OP70_g425__5122(.A (D_r_reg[3]), .B (B_i_reg[3]), .CI
       (ADD_TC_OP70_n_4), .CO (ADD_TC_OP70_n_6), .S (X3_i_w[3]));
  ADDFX1 ADD_TC_OP70_g426__8246(.A (D_r_reg[2]), .B (B_i_reg[2]), .CI
       (ADD_TC_OP70_n_2), .CO (ADD_TC_OP70_n_4), .S (X3_i_w[2]));
  ADDFX1 ADD_TC_OP70_g427__7098(.A (D_r_reg[1]), .B (B_i_reg[1]), .CI
       (ADD_TC_OP70_n_0), .CO (ADD_TC_OP70_n_2), .S (X3_i_w[1]));
  AOI2BB1X1 ADD_TC_OP70_g428__6131(.A0N (B_i_reg[0]), .A1N
       (D_r_reg[0]), .B0 (ADD_TC_OP70_n_0), .Y (X3_i_w[0]));
  AND2X1 ADD_TC_OP70_g429__1881(.A (D_r_reg[0]), .B (B_i_reg[0]), .Y
       (ADD_TC_OP70_n_0));
  INVXL ADD_TC_OP72_g386(.A (ADD_TC_OP72_n_32), .Y (C_i[15]));
  ADDFXL ADD_TC_OP72_g387__5115(.A (x1_i_reg[15]), .B (x3_i_reg[15]),
       .CI (ADD_TC_OP72_n_30), .CO (C_i[16]), .S (ADD_TC_OP72_n_32));
  INVX1 ADD_TC_OP72_g388(.A (ADD_TC_OP72_n_28), .Y (ADD_TC_OP72_n_30));
  ADDFXL ADD_TC_OP72_g389__7482(.A (x1_i_reg[14]), .B (x3_i_reg[14]),
       .CI (ADD_TC_OP72_n_26), .CO (ADD_TC_OP72_n_28), .S (C_i[14]));
  ADDFX1 ADD_TC_OP72_g390__4733(.A (x3_i_reg[13]), .B (x1_i_reg[13]),
       .CI (ADD_TC_OP72_n_24), .CO (ADD_TC_OP72_n_26), .S (C_i[13]));
  ADDFX1 ADD_TC_OP72_g391__6161(.A (x3_i_reg[12]), .B (x1_i_reg[12]),
       .CI (ADD_TC_OP72_n_22), .CO (ADD_TC_OP72_n_24), .S (C_i[12]));
  ADDFX1 ADD_TC_OP72_g392__9315(.A (x3_i_reg[11]), .B (x1_i_reg[11]),
       .CI (ADD_TC_OP72_n_20), .CO (ADD_TC_OP72_n_22), .S (C_i[11]));
  ADDFX1 ADD_TC_OP72_g393__9945(.A (x3_i_reg[10]), .B (x1_i_reg[10]),
       .CI (ADD_TC_OP72_n_18), .CO (ADD_TC_OP72_n_20), .S (C_i[10]));
  ADDFX1 ADD_TC_OP72_g394__2883(.A (x3_i_reg[9]), .B (x1_i_reg[9]), .CI
       (ADD_TC_OP72_n_16), .CO (ADD_TC_OP72_n_18), .S (C_i[9]));
  ADDFX1 ADD_TC_OP72_g395__2346(.A (x3_i_reg[8]), .B (x1_i_reg[8]), .CI
       (ADD_TC_OP72_n_14), .CO (ADD_TC_OP72_n_16), .S (C_i[8]));
  ADDFX1 ADD_TC_OP72_g396__1666(.A (x3_i_reg[7]), .B (x1_i_reg[7]), .CI
       (ADD_TC_OP72_n_12), .CO (ADD_TC_OP72_n_14), .S (C_i[7]));
  ADDFX1 ADD_TC_OP72_g397__7410(.A (x3_i_reg[6]), .B (x1_i_reg[6]), .CI
       (ADD_TC_OP72_n_10), .CO (ADD_TC_OP72_n_12), .S (C_i[6]));
  ADDFX1 ADD_TC_OP72_g398__6417(.A (x3_i_reg[5]), .B (x1_i_reg[5]), .CI
       (ADD_TC_OP72_n_8), .CO (ADD_TC_OP72_n_10), .S (C_i[5]));
  ADDFX1 ADD_TC_OP72_g399__5477(.A (x3_i_reg[4]), .B (x1_i_reg[4]), .CI
       (ADD_TC_OP72_n_6), .CO (ADD_TC_OP72_n_8), .S (C_i[4]));
  ADDFX1 ADD_TC_OP72_g400__2398(.A (x3_i_reg[3]), .B (x1_i_reg[3]), .CI
       (ADD_TC_OP72_n_4), .CO (ADD_TC_OP72_n_6), .S (C_i[3]));
  ADDFX1 ADD_TC_OP72_g401__5107(.A (x3_i_reg[2]), .B (x1_i_reg[2]), .CI
       (ADD_TC_OP72_n_2), .CO (ADD_TC_OP72_n_4), .S (C_i[2]));
  ADDFX1 ADD_TC_OP72_g402__6260(.A (x3_i_reg[1]), .B (x1_i_reg[1]), .CI
       (ADD_TC_OP72_n_0), .CO (ADD_TC_OP72_n_2), .S (C_i[1]));
  AOI2BB1X1 ADD_TC_OP72_g403__4319(.A0N (x1_i_reg[0]), .A1N
       (x3_i_reg[0]), .B0 (ADD_TC_OP72_n_0), .Y (C_i[0]));
  AND2X1 ADD_TC_OP72_g404__8428(.A (x3_i_reg[0]), .B (x1_i_reg[0]), .Y
       (ADD_TC_OP72_n_0));
  INVXL ADD_TC_OP74_g386(.A (ADD_TC_OP74_n_32), .Y (C_r[15]));
  ADDFXL ADD_TC_OP74_g387__5526(.A (x1_r_reg[15]), .B (x3_r_reg[15]),
       .CI (ADD_TC_OP74_n_30), .CO (C_r[16]), .S (ADD_TC_OP74_n_32));
  INVX1 ADD_TC_OP74_g388(.A (ADD_TC_OP74_n_28), .Y (ADD_TC_OP74_n_30));
  ADDFXL ADD_TC_OP74_g389__6783(.A (x1_r_reg[14]), .B (x3_r_reg[14]),
       .CI (ADD_TC_OP74_n_26), .CO (ADD_TC_OP74_n_28), .S (C_r[14]));
  ADDFX1 ADD_TC_OP74_g390__3680(.A (x3_r_reg[13]), .B (x1_r_reg[13]),
       .CI (ADD_TC_OP74_n_24), .CO (ADD_TC_OP74_n_26), .S (C_r[13]));
  ADDFX1 ADD_TC_OP74_g391__1617(.A (x3_r_reg[12]), .B (x1_r_reg[12]),
       .CI (ADD_TC_OP74_n_22), .CO (ADD_TC_OP74_n_24), .S (C_r[12]));
  ADDFX1 ADD_TC_OP74_g392__2802(.A (x3_r_reg[11]), .B (x1_r_reg[11]),
       .CI (ADD_TC_OP74_n_20), .CO (ADD_TC_OP74_n_22), .S (C_r[11]));
  ADDFX1 ADD_TC_OP74_g393__1705(.A (x3_r_reg[10]), .B (x1_r_reg[10]),
       .CI (ADD_TC_OP74_n_18), .CO (ADD_TC_OP74_n_20), .S (C_r[10]));
  ADDFX1 ADD_TC_OP74_g394__5122(.A (x3_r_reg[9]), .B (x1_r_reg[9]), .CI
       (ADD_TC_OP74_n_16), .CO (ADD_TC_OP74_n_18), .S (C_r[9]));
  ADDFX1 ADD_TC_OP74_g395__8246(.A (x3_r_reg[8]), .B (x1_r_reg[8]), .CI
       (ADD_TC_OP74_n_14), .CO (ADD_TC_OP74_n_16), .S (C_r[8]));
  ADDFX1 ADD_TC_OP74_g396__7098(.A (x3_r_reg[7]), .B (x1_r_reg[7]), .CI
       (ADD_TC_OP74_n_12), .CO (ADD_TC_OP74_n_14), .S (C_r[7]));
  ADDFX1 ADD_TC_OP74_g397__6131(.A (x3_r_reg[6]), .B (x1_r_reg[6]), .CI
       (ADD_TC_OP74_n_10), .CO (ADD_TC_OP74_n_12), .S (C_r[6]));
  ADDFX1 ADD_TC_OP74_g398__1881(.A (x3_r_reg[5]), .B (x1_r_reg[5]), .CI
       (ADD_TC_OP74_n_8), .CO (ADD_TC_OP74_n_10), .S (C_r[5]));
  ADDFX1 ADD_TC_OP74_g399__5115(.A (x3_r_reg[4]), .B (x1_r_reg[4]), .CI
       (ADD_TC_OP74_n_6), .CO (ADD_TC_OP74_n_8), .S (C_r[4]));
  ADDFX1 ADD_TC_OP74_g400__7482(.A (x3_r_reg[3]), .B (x1_r_reg[3]), .CI
       (ADD_TC_OP74_n_4), .CO (ADD_TC_OP74_n_6), .S (C_r[3]));
  ADDFX1 ADD_TC_OP74_g401__4733(.A (x3_r_reg[2]), .B (x1_r_reg[2]), .CI
       (ADD_TC_OP74_n_2), .CO (ADD_TC_OP74_n_4), .S (C_r[2]));
  ADDFX1 ADD_TC_OP74_g402__6161(.A (x3_r_reg[1]), .B (x1_r_reg[1]), .CI
       (ADD_TC_OP74_n_0), .CO (ADD_TC_OP74_n_2), .S (C_r[1]));
  AOI2BB1X1 ADD_TC_OP74_g403__9315(.A0N (x1_r_reg[0]), .A1N
       (x3_r_reg[0]), .B0 (ADD_TC_OP74_n_0), .Y (C_r[0]));
  AND2X1 ADD_TC_OP74_g404__9945(.A (x3_r_reg[0]), .B (x1_r_reg[0]), .Y
       (ADD_TC_OP74_n_0));
  INVXL ADD_TC_OP76_g386(.A (ADD_TC_OP76_n_32), .Y (A_i[15]));
  ADDFXL ADD_TC_OP76_g387__2883(.A (x0_i_reg[15]), .B (x2_i_reg[15]),
       .CI (ADD_TC_OP76_n_30), .CO (A_i[16]), .S (ADD_TC_OP76_n_32));
  INVX1 ADD_TC_OP76_g388(.A (ADD_TC_OP76_n_28), .Y (ADD_TC_OP76_n_30));
  ADDFXL ADD_TC_OP76_g389__2346(.A (x0_i_reg[14]), .B (x2_i_reg[14]),
       .CI (ADD_TC_OP76_n_26), .CO (ADD_TC_OP76_n_28), .S (A_i[14]));
  ADDFX1 ADD_TC_OP76_g390__1666(.A (x2_i_reg[13]), .B (x0_i_reg[13]),
       .CI (ADD_TC_OP76_n_24), .CO (ADD_TC_OP76_n_26), .S (A_i[13]));
  ADDFX1 ADD_TC_OP76_g391__7410(.A (x2_i_reg[12]), .B (x0_i_reg[12]),
       .CI (ADD_TC_OP76_n_22), .CO (ADD_TC_OP76_n_24), .S (A_i[12]));
  ADDFX1 ADD_TC_OP76_g392__6417(.A (x2_i_reg[11]), .B (x0_i_reg[11]),
       .CI (ADD_TC_OP76_n_20), .CO (ADD_TC_OP76_n_22), .S (A_i[11]));
  ADDFX1 ADD_TC_OP76_g393__5477(.A (x2_i_reg[10]), .B (x0_i_reg[10]),
       .CI (ADD_TC_OP76_n_18), .CO (ADD_TC_OP76_n_20), .S (A_i[10]));
  ADDFX1 ADD_TC_OP76_g394__2398(.A (x2_i_reg[9]), .B (x0_i_reg[9]), .CI
       (ADD_TC_OP76_n_16), .CO (ADD_TC_OP76_n_18), .S (A_i[9]));
  ADDFX1 ADD_TC_OP76_g395__5107(.A (x2_i_reg[8]), .B (x0_i_reg[8]), .CI
       (ADD_TC_OP76_n_14), .CO (ADD_TC_OP76_n_16), .S (A_i[8]));
  ADDFX1 ADD_TC_OP76_g396__6260(.A (x2_i_reg[7]), .B (x0_i_reg[7]), .CI
       (ADD_TC_OP76_n_12), .CO (ADD_TC_OP76_n_14), .S (A_i[7]));
  ADDFX1 ADD_TC_OP76_g397__4319(.A (x2_i_reg[6]), .B (x0_i_reg[6]), .CI
       (ADD_TC_OP76_n_10), .CO (ADD_TC_OP76_n_12), .S (A_i[6]));
  ADDFX1 ADD_TC_OP76_g398__8428(.A (x2_i_reg[5]), .B (x0_i_reg[5]), .CI
       (ADD_TC_OP76_n_8), .CO (ADD_TC_OP76_n_10), .S (A_i[5]));
  ADDFX1 ADD_TC_OP76_g399__5526(.A (x2_i_reg[4]), .B (x0_i_reg[4]), .CI
       (ADD_TC_OP76_n_6), .CO (ADD_TC_OP76_n_8), .S (A_i[4]));
  ADDFX1 ADD_TC_OP76_g400__6783(.A (x2_i_reg[3]), .B (x0_i_reg[3]), .CI
       (ADD_TC_OP76_n_4), .CO (ADD_TC_OP76_n_6), .S (A_i[3]));
  ADDFX1 ADD_TC_OP76_g401__3680(.A (x2_i_reg[2]), .B (x0_i_reg[2]), .CI
       (ADD_TC_OP76_n_2), .CO (ADD_TC_OP76_n_4), .S (A_i[2]));
  ADDFX1 ADD_TC_OP76_g402__1617(.A (x2_i_reg[1]), .B (x0_i_reg[1]), .CI
       (ADD_TC_OP76_n_0), .CO (ADD_TC_OP76_n_2), .S (A_i[1]));
  AOI2BB1X1 ADD_TC_OP76_g403__2802(.A0N (x0_i_reg[0]), .A1N
       (x2_i_reg[0]), .B0 (ADD_TC_OP76_n_0), .Y (A_i[0]));
  AND2X1 ADD_TC_OP76_g404__1705(.A (x2_i_reg[0]), .B (x0_i_reg[0]), .Y
       (ADD_TC_OP76_n_0));
  INVXL ADD_TC_OP78_g386(.A (ADD_TC_OP78_n_32), .Y (A_r[15]));
  ADDFXL ADD_TC_OP78_g387__5122(.A (x0_r_reg[15]), .B (x2_r_reg[15]),
       .CI (ADD_TC_OP78_n_30), .CO (A_r[16]), .S (ADD_TC_OP78_n_32));
  INVX1 ADD_TC_OP78_g388(.A (ADD_TC_OP78_n_28), .Y (ADD_TC_OP78_n_30));
  ADDFXL ADD_TC_OP78_g389__8246(.A (x0_r_reg[14]), .B (x2_r_reg[14]),
       .CI (ADD_TC_OP78_n_26), .CO (ADD_TC_OP78_n_28), .S (A_r[14]));
  ADDFX1 ADD_TC_OP78_g390__7098(.A (x2_r_reg[13]), .B (x0_r_reg[13]),
       .CI (ADD_TC_OP78_n_24), .CO (ADD_TC_OP78_n_26), .S (A_r[13]));
  ADDFX1 ADD_TC_OP78_g391__6131(.A (x2_r_reg[12]), .B (x0_r_reg[12]),
       .CI (ADD_TC_OP78_n_22), .CO (ADD_TC_OP78_n_24), .S (A_r[12]));
  ADDFX1 ADD_TC_OP78_g392__1881(.A (x2_r_reg[11]), .B (x0_r_reg[11]),
       .CI (ADD_TC_OP78_n_20), .CO (ADD_TC_OP78_n_22), .S (A_r[11]));
  ADDFX1 ADD_TC_OP78_g393__5115(.A (x2_r_reg[10]), .B (x0_r_reg[10]),
       .CI (ADD_TC_OP78_n_18), .CO (ADD_TC_OP78_n_20), .S (A_r[10]));
  ADDFX1 ADD_TC_OP78_g394__7482(.A (x2_r_reg[9]), .B (x0_r_reg[9]), .CI
       (ADD_TC_OP78_n_16), .CO (ADD_TC_OP78_n_18), .S (A_r[9]));
  ADDFX1 ADD_TC_OP78_g395__4733(.A (x2_r_reg[8]), .B (x0_r_reg[8]), .CI
       (ADD_TC_OP78_n_14), .CO (ADD_TC_OP78_n_16), .S (A_r[8]));
  ADDFX1 ADD_TC_OP78_g396__6161(.A (x2_r_reg[7]), .B (x0_r_reg[7]), .CI
       (ADD_TC_OP78_n_12), .CO (ADD_TC_OP78_n_14), .S (A_r[7]));
  ADDFX1 ADD_TC_OP78_g397__9315(.A (x2_r_reg[6]), .B (x0_r_reg[6]), .CI
       (ADD_TC_OP78_n_10), .CO (ADD_TC_OP78_n_12), .S (A_r[6]));
  ADDFX1 ADD_TC_OP78_g398__9945(.A (x2_r_reg[5]), .B (x0_r_reg[5]), .CI
       (ADD_TC_OP78_n_8), .CO (ADD_TC_OP78_n_10), .S (A_r[5]));
  ADDFX1 ADD_TC_OP78_g399__2883(.A (x2_r_reg[4]), .B (x0_r_reg[4]), .CI
       (ADD_TC_OP78_n_6), .CO (ADD_TC_OP78_n_8), .S (A_r[4]));
  ADDFX1 ADD_TC_OP78_g400__2346(.A (x2_r_reg[3]), .B (x0_r_reg[3]), .CI
       (ADD_TC_OP78_n_4), .CO (ADD_TC_OP78_n_6), .S (A_r[3]));
  ADDFX1 ADD_TC_OP78_g401__1666(.A (x2_r_reg[2]), .B (x0_r_reg[2]), .CI
       (ADD_TC_OP78_n_2), .CO (ADD_TC_OP78_n_4), .S (A_r[2]));
  ADDFX1 ADD_TC_OP78_g402__7410(.A (x2_r_reg[1]), .B (x0_r_reg[1]), .CI
       (ADD_TC_OP78_n_0), .CO (ADD_TC_OP78_n_2), .S (A_r[1]));
  AOI2BB1X1 ADD_TC_OP78_g403__6417(.A0N (x0_r_reg[0]), .A1N
       (x2_r_reg[0]), .B0 (ADD_TC_OP78_n_0), .Y (A_r[0]));
  AND2X1 ADD_TC_OP78_g404__5477(.A (x2_r_reg[0]), .B (x0_r_reg[0]), .Y
       (ADD_TC_OP78_n_0));
  OAI22X1 SUB_TC_OP_g477__2398(.A0 (SUB_TC_OP_n_17), .A1
       (SUB_TC_OP_n_50), .B0 (D_i_reg[16]), .B1 (SUB_TC_OP_n_10), .Y
       (X3_r_w[17]));
  OAI21X1 SUB_TC_OP_g478__5107(.A0 (SUB_TC_OP_n_19), .A1
       (SUB_TC_OP_n_50), .B0 (SUB_TC_OP_n_51), .Y (X3_r_w[16]));
  NAND2XL SUB_TC_OP_g479__6260(.A (SUB_TC_OP_n_19), .B
       (SUB_TC_OP_n_50), .Y (SUB_TC_OP_n_51));
  ADDFX1 SUB_TC_OP_g480__4319(.A (SUB_TC_OP_n_2), .B (B_r_reg[15]), .CI
       (SUB_TC_OP_n_47), .CO (SUB_TC_OP_n_50), .S (X3_r_w[15]));
  ADDFX1 SUB_TC_OP_g481__8428(.A (SUB_TC_OP_n_12), .B (B_r_reg[14]),
       .CI (SUB_TC_OP_n_45), .CO (SUB_TC_OP_n_47), .S (X3_r_w[14]));
  ADDFX1 SUB_TC_OP_g482__5526(.A (SUB_TC_OP_n_0), .B (B_r_reg[13]), .CI
       (SUB_TC_OP_n_43), .CO (SUB_TC_OP_n_45), .S (X3_r_w[13]));
  ADDFX1 SUB_TC_OP_g483__6783(.A (SUB_TC_OP_n_5), .B (B_r_reg[12]), .CI
       (SUB_TC_OP_n_41), .CO (SUB_TC_OP_n_43), .S (X3_r_w[12]));
  ADDFX1 SUB_TC_OP_g484__3680(.A (SUB_TC_OP_n_8), .B (B_r_reg[11]), .CI
       (SUB_TC_OP_n_39), .CO (SUB_TC_OP_n_41), .S (X3_r_w[11]));
  ADDFX1 SUB_TC_OP_g485__1617(.A (SUB_TC_OP_n_11), .B (B_r_reg[10]),
       .CI (SUB_TC_OP_n_37), .CO (SUB_TC_OP_n_39), .S (X3_r_w[10]));
  ADDFX1 SUB_TC_OP_g486__2802(.A (SUB_TC_OP_n_3), .B (B_r_reg[9]), .CI
       (SUB_TC_OP_n_35), .CO (SUB_TC_OP_n_37), .S (X3_r_w[9]));
  ADDFX1 SUB_TC_OP_g487__1705(.A (SUB_TC_OP_n_9), .B (B_r_reg[8]), .CI
       (SUB_TC_OP_n_33), .CO (SUB_TC_OP_n_35), .S (X3_r_w[8]));
  ADDFX1 SUB_TC_OP_g488__5122(.A (SUB_TC_OP_n_16), .B (B_r_reg[7]), .CI
       (SUB_TC_OP_n_31), .CO (SUB_TC_OP_n_33), .S (X3_r_w[7]));
  ADDFX1 SUB_TC_OP_g489__8246(.A (SUB_TC_OP_n_1), .B (B_r_reg[6]), .CI
       (SUB_TC_OP_n_29), .CO (SUB_TC_OP_n_31), .S (X3_r_w[6]));
  ADDFX1 SUB_TC_OP_g490__7098(.A (SUB_TC_OP_n_7), .B (B_r_reg[5]), .CI
       (SUB_TC_OP_n_27), .CO (SUB_TC_OP_n_29), .S (X3_r_w[5]));
  ADDFX1 SUB_TC_OP_g491__6131(.A (SUB_TC_OP_n_4), .B (B_r_reg[4]), .CI
       (SUB_TC_OP_n_25), .CO (SUB_TC_OP_n_27), .S (X3_r_w[4]));
  ADDFX1 SUB_TC_OP_g492__1881(.A (SUB_TC_OP_n_15), .B (B_r_reg[3]), .CI
       (SUB_TC_OP_n_23), .CO (SUB_TC_OP_n_25), .S (X3_r_w[3]));
  ADDFX1 SUB_TC_OP_g493__5115(.A (SUB_TC_OP_n_14), .B (B_r_reg[2]), .CI
       (SUB_TC_OP_n_21), .CO (SUB_TC_OP_n_23), .S (X3_r_w[2]));
  ADDFX1 SUB_TC_OP_g494__7482(.A (SUB_TC_OP_n_13), .B (B_r_reg[1]), .CI
       (SUB_TC_OP_n_18), .CO (SUB_TC_OP_n_21), .S (X3_r_w[1]));
  OAI21X1 SUB_TC_OP_g495__4733(.A0 (D_i_reg[0]), .A1 (SUB_TC_OP_n_6),
       .B0 (SUB_TC_OP_n_18), .Y (X3_r_w[0]));
  MXI2XL SUB_TC_OP_g496__6161(.A (SUB_TC_OP_n_10), .B (B_r_reg[16]),
       .S0 (D_i_reg[16]), .Y (SUB_TC_OP_n_19));
  NAND2XL SUB_TC_OP_g497__9315(.A (D_i_reg[0]), .B (SUB_TC_OP_n_6), .Y
       (SUB_TC_OP_n_18));
  NOR2BX1 SUB_TC_OP_g498__9945(.AN (D_i_reg[16]), .B (B_r_reg[16]), .Y
       (SUB_TC_OP_n_17));
  OAI22X1 SUB_TC_OP67_g477__2883(.A0 (SUB_TC_OP67_n_17), .A1
       (SUB_TC_OP67_n_50), .B0 (C_i_reg[16]), .B1 (SUB_TC_OP67_n_10),
       .Y (X2_i_w[17]));
  OAI21X1 SUB_TC_OP67_g478__2346(.A0 (SUB_TC_OP67_n_19), .A1
       (SUB_TC_OP67_n_50), .B0 (SUB_TC_OP67_n_51), .Y (X2_i_w[16]));
  NAND2XL SUB_TC_OP67_g479__1666(.A (SUB_TC_OP67_n_19), .B
       (SUB_TC_OP67_n_50), .Y (SUB_TC_OP67_n_51));
  ADDFX1 SUB_TC_OP67_g480__7410(.A (SUB_TC_OP67_n_2), .B (A_i_reg[15]),
       .CI (SUB_TC_OP67_n_47), .CO (SUB_TC_OP67_n_50), .S (X2_i_w[15]));
  ADDFX1 SUB_TC_OP67_g481__6417(.A (SUB_TC_OP67_n_12), .B
       (A_i_reg[14]), .CI (SUB_TC_OP67_n_45), .CO (SUB_TC_OP67_n_47),
       .S (X2_i_w[14]));
  ADDFX1 SUB_TC_OP67_g482__5477(.A (SUB_TC_OP67_n_0), .B (A_i_reg[13]),
       .CI (SUB_TC_OP67_n_43), .CO (SUB_TC_OP67_n_45), .S (X2_i_w[13]));
  ADDFX1 SUB_TC_OP67_g483__2398(.A (SUB_TC_OP67_n_5), .B (A_i_reg[12]),
       .CI (SUB_TC_OP67_n_41), .CO (SUB_TC_OP67_n_43), .S (X2_i_w[12]));
  ADDFX1 SUB_TC_OP67_g484__5107(.A (SUB_TC_OP67_n_8), .B (A_i_reg[11]),
       .CI (SUB_TC_OP67_n_39), .CO (SUB_TC_OP67_n_41), .S (X2_i_w[11]));
  ADDFX1 SUB_TC_OP67_g485__6260(.A (SUB_TC_OP67_n_11), .B
       (A_i_reg[10]), .CI (SUB_TC_OP67_n_37), .CO (SUB_TC_OP67_n_39),
       .S (X2_i_w[10]));
  ADDFX1 SUB_TC_OP67_g486__4319(.A (SUB_TC_OP67_n_3), .B (A_i_reg[9]),
       .CI (SUB_TC_OP67_n_35), .CO (SUB_TC_OP67_n_37), .S (X2_i_w[9]));
  ADDFX1 SUB_TC_OP67_g487__8428(.A (SUB_TC_OP67_n_9), .B (A_i_reg[8]),
       .CI (SUB_TC_OP67_n_33), .CO (SUB_TC_OP67_n_35), .S (X2_i_w[8]));
  ADDFX1 SUB_TC_OP67_g488__5526(.A (SUB_TC_OP67_n_16), .B (A_i_reg[7]),
       .CI (SUB_TC_OP67_n_31), .CO (SUB_TC_OP67_n_33), .S (X2_i_w[7]));
  ADDFX1 SUB_TC_OP67_g489__6783(.A (SUB_TC_OP67_n_1), .B (A_i_reg[6]),
       .CI (SUB_TC_OP67_n_29), .CO (SUB_TC_OP67_n_31), .S (X2_i_w[6]));
  ADDFX1 SUB_TC_OP67_g490__3680(.A (SUB_TC_OP67_n_7), .B (A_i_reg[5]),
       .CI (SUB_TC_OP67_n_27), .CO (SUB_TC_OP67_n_29), .S (X2_i_w[5]));
  ADDFX1 SUB_TC_OP67_g491__1617(.A (SUB_TC_OP67_n_4), .B (A_i_reg[4]),
       .CI (SUB_TC_OP67_n_25), .CO (SUB_TC_OP67_n_27), .S (X2_i_w[4]));
  ADDFX1 SUB_TC_OP67_g492__2802(.A (SUB_TC_OP67_n_15), .B (A_i_reg[3]),
       .CI (SUB_TC_OP67_n_23), .CO (SUB_TC_OP67_n_25), .S (X2_i_w[3]));
  ADDFX1 SUB_TC_OP67_g493__1705(.A (SUB_TC_OP67_n_14), .B (A_i_reg[2]),
       .CI (SUB_TC_OP67_n_21), .CO (SUB_TC_OP67_n_23), .S (X2_i_w[2]));
  ADDFX1 SUB_TC_OP67_g494__5122(.A (SUB_TC_OP67_n_13), .B (A_i_reg[1]),
       .CI (SUB_TC_OP67_n_18), .CO (SUB_TC_OP67_n_21), .S (X2_i_w[1]));
  OAI21X1 SUB_TC_OP67_g495__8246(.A0 (C_i_reg[0]), .A1
       (SUB_TC_OP67_n_6), .B0 (SUB_TC_OP67_n_18), .Y (X2_i_w[0]));
  MXI2XL SUB_TC_OP67_g496__7098(.A (SUB_TC_OP67_n_10), .B
       (A_i_reg[16]), .S0 (C_i_reg[16]), .Y (SUB_TC_OP67_n_19));
  NAND2XL SUB_TC_OP67_g497__6131(.A (C_i_reg[0]), .B (SUB_TC_OP67_n_6),
       .Y (SUB_TC_OP67_n_18));
  NOR2BX1 SUB_TC_OP67_g498__1881(.AN (C_i_reg[16]), .B (A_i_reg[16]),
       .Y (SUB_TC_OP67_n_17));
  OAI22X1 SUB_TC_OP69_g477__5115(.A0 (SUB_TC_OP69_n_17), .A1
       (SUB_TC_OP69_n_50), .B0 (C_r_reg[16]), .B1 (SUB_TC_OP69_n_10),
       .Y (X2_r_w[17]));
  OAI21X1 SUB_TC_OP69_g478__7482(.A0 (SUB_TC_OP69_n_19), .A1
       (SUB_TC_OP69_n_50), .B0 (SUB_TC_OP69_n_51), .Y (X2_r_w[16]));
  NAND2XL SUB_TC_OP69_g479__4733(.A (SUB_TC_OP69_n_19), .B
       (SUB_TC_OP69_n_50), .Y (SUB_TC_OP69_n_51));
  ADDFX1 SUB_TC_OP69_g480__6161(.A (SUB_TC_OP69_n_2), .B (A_r_reg[15]),
       .CI (SUB_TC_OP69_n_47), .CO (SUB_TC_OP69_n_50), .S (X2_r_w[15]));
  ADDFX1 SUB_TC_OP69_g481__9315(.A (SUB_TC_OP69_n_12), .B
       (A_r_reg[14]), .CI (SUB_TC_OP69_n_45), .CO (SUB_TC_OP69_n_47),
       .S (X2_r_w[14]));
  ADDFX1 SUB_TC_OP69_g482__9945(.A (SUB_TC_OP69_n_0), .B (A_r_reg[13]),
       .CI (SUB_TC_OP69_n_43), .CO (SUB_TC_OP69_n_45), .S (X2_r_w[13]));
  ADDFX1 SUB_TC_OP69_g483__2883(.A (SUB_TC_OP69_n_5), .B (A_r_reg[12]),
       .CI (SUB_TC_OP69_n_41), .CO (SUB_TC_OP69_n_43), .S (X2_r_w[12]));
  ADDFX1 SUB_TC_OP69_g484__2346(.A (SUB_TC_OP69_n_8), .B (A_r_reg[11]),
       .CI (SUB_TC_OP69_n_39), .CO (SUB_TC_OP69_n_41), .S (X2_r_w[11]));
  ADDFX1 SUB_TC_OP69_g485__1666(.A (SUB_TC_OP69_n_11), .B
       (A_r_reg[10]), .CI (SUB_TC_OP69_n_37), .CO (SUB_TC_OP69_n_39),
       .S (X2_r_w[10]));
  ADDFX1 SUB_TC_OP69_g486__7410(.A (SUB_TC_OP69_n_3), .B (A_r_reg[9]),
       .CI (SUB_TC_OP69_n_35), .CO (SUB_TC_OP69_n_37), .S (X2_r_w[9]));
  ADDFX1 SUB_TC_OP69_g487__6417(.A (SUB_TC_OP69_n_9), .B (A_r_reg[8]),
       .CI (SUB_TC_OP69_n_33), .CO (SUB_TC_OP69_n_35), .S (X2_r_w[8]));
  ADDFX1 SUB_TC_OP69_g488__5477(.A (SUB_TC_OP69_n_16), .B (A_r_reg[7]),
       .CI (SUB_TC_OP69_n_31), .CO (SUB_TC_OP69_n_33), .S (X2_r_w[7]));
  ADDFX1 SUB_TC_OP69_g489__2398(.A (SUB_TC_OP69_n_1), .B (A_r_reg[6]),
       .CI (SUB_TC_OP69_n_29), .CO (SUB_TC_OP69_n_31), .S (X2_r_w[6]));
  ADDFX1 SUB_TC_OP69_g490__5107(.A (SUB_TC_OP69_n_7), .B (A_r_reg[5]),
       .CI (SUB_TC_OP69_n_27), .CO (SUB_TC_OP69_n_29), .S (X2_r_w[5]));
  ADDFX1 SUB_TC_OP69_g491__6260(.A (SUB_TC_OP69_n_4), .B (A_r_reg[4]),
       .CI (SUB_TC_OP69_n_25), .CO (SUB_TC_OP69_n_27), .S (X2_r_w[4]));
  ADDFX1 SUB_TC_OP69_g492__4319(.A (SUB_TC_OP69_n_15), .B (A_r_reg[3]),
       .CI (SUB_TC_OP69_n_23), .CO (SUB_TC_OP69_n_25), .S (X2_r_w[3]));
  ADDFX1 SUB_TC_OP69_g493__8428(.A (SUB_TC_OP69_n_14), .B (A_r_reg[2]),
       .CI (SUB_TC_OP69_n_21), .CO (SUB_TC_OP69_n_23), .S (X2_r_w[2]));
  ADDFX1 SUB_TC_OP69_g494__5526(.A (SUB_TC_OP69_n_13), .B (A_r_reg[1]),
       .CI (SUB_TC_OP69_n_18), .CO (SUB_TC_OP69_n_21), .S (X2_r_w[1]));
  OAI21X1 SUB_TC_OP69_g495__6783(.A0 (C_r_reg[0]), .A1
       (SUB_TC_OP69_n_6), .B0 (SUB_TC_OP69_n_18), .Y (X2_r_w[0]));
  MXI2XL SUB_TC_OP69_g496__3680(.A (SUB_TC_OP69_n_10), .B
       (A_r_reg[16]), .S0 (C_r_reg[16]), .Y (SUB_TC_OP69_n_19));
  NAND2XL SUB_TC_OP69_g497__1617(.A (C_r_reg[0]), .B (SUB_TC_OP69_n_6),
       .Y (SUB_TC_OP69_n_18));
  NOR2BX1 SUB_TC_OP69_g498__2802(.AN (C_r_reg[16]), .B (A_r_reg[16]),
       .Y (SUB_TC_OP69_n_17));
  OAI22X1 SUB_TC_OP71_g477__1705(.A0 (SUB_TC_OP71_n_17), .A1
       (SUB_TC_OP71_n_50), .B0 (D_r_reg[16]), .B1 (SUB_TC_OP71_n_10),
       .Y (X1_i_w[17]));
  OAI21X1 SUB_TC_OP71_g478__5122(.A0 (SUB_TC_OP71_n_19), .A1
       (SUB_TC_OP71_n_50), .B0 (SUB_TC_OP71_n_51), .Y (X1_i_w[16]));
  NAND2XL SUB_TC_OP71_g479__8246(.A (SUB_TC_OP71_n_19), .B
       (SUB_TC_OP71_n_50), .Y (SUB_TC_OP71_n_51));
  ADDFX1 SUB_TC_OP71_g480__7098(.A (SUB_TC_OP71_n_2), .B (B_i_reg[15]),
       .CI (SUB_TC_OP71_n_47), .CO (SUB_TC_OP71_n_50), .S (X1_i_w[15]));
  ADDFX1 SUB_TC_OP71_g481__6131(.A (SUB_TC_OP71_n_12), .B
       (B_i_reg[14]), .CI (SUB_TC_OP71_n_45), .CO (SUB_TC_OP71_n_47),
       .S (X1_i_w[14]));
  ADDFX1 SUB_TC_OP71_g482__1881(.A (SUB_TC_OP71_n_0), .B (B_i_reg[13]),
       .CI (SUB_TC_OP71_n_43), .CO (SUB_TC_OP71_n_45), .S (X1_i_w[13]));
  ADDFX1 SUB_TC_OP71_g483__5115(.A (SUB_TC_OP71_n_5), .B (B_i_reg[12]),
       .CI (SUB_TC_OP71_n_41), .CO (SUB_TC_OP71_n_43), .S (X1_i_w[12]));
  ADDFX1 SUB_TC_OP71_g484__7482(.A (SUB_TC_OP71_n_8), .B (B_i_reg[11]),
       .CI (SUB_TC_OP71_n_39), .CO (SUB_TC_OP71_n_41), .S (X1_i_w[11]));
  ADDFX1 SUB_TC_OP71_g485__4733(.A (SUB_TC_OP71_n_11), .B
       (B_i_reg[10]), .CI (SUB_TC_OP71_n_37), .CO (SUB_TC_OP71_n_39),
       .S (X1_i_w[10]));
  ADDFX1 SUB_TC_OP71_g486__6161(.A (SUB_TC_OP71_n_3), .B (B_i_reg[9]),
       .CI (SUB_TC_OP71_n_35), .CO (SUB_TC_OP71_n_37), .S (X1_i_w[9]));
  ADDFX1 SUB_TC_OP71_g487__9315(.A (SUB_TC_OP71_n_9), .B (B_i_reg[8]),
       .CI (SUB_TC_OP71_n_33), .CO (SUB_TC_OP71_n_35), .S (X1_i_w[8]));
  ADDFX1 SUB_TC_OP71_g488__9945(.A (SUB_TC_OP71_n_16), .B (B_i_reg[7]),
       .CI (SUB_TC_OP71_n_31), .CO (SUB_TC_OP71_n_33), .S (X1_i_w[7]));
  ADDFX1 SUB_TC_OP71_g489__2883(.A (SUB_TC_OP71_n_1), .B (B_i_reg[6]),
       .CI (SUB_TC_OP71_n_29), .CO (SUB_TC_OP71_n_31), .S (X1_i_w[6]));
  ADDFX1 SUB_TC_OP71_g490__2346(.A (SUB_TC_OP71_n_7), .B (B_i_reg[5]),
       .CI (SUB_TC_OP71_n_27), .CO (SUB_TC_OP71_n_29), .S (X1_i_w[5]));
  ADDFX1 SUB_TC_OP71_g491__1666(.A (SUB_TC_OP71_n_4), .B (B_i_reg[4]),
       .CI (SUB_TC_OP71_n_25), .CO (SUB_TC_OP71_n_27), .S (X1_i_w[4]));
  ADDFX1 SUB_TC_OP71_g492__7410(.A (SUB_TC_OP71_n_15), .B (B_i_reg[3]),
       .CI (SUB_TC_OP71_n_23), .CO (SUB_TC_OP71_n_25), .S (X1_i_w[3]));
  ADDFX1 SUB_TC_OP71_g493__6417(.A (SUB_TC_OP71_n_14), .B (B_i_reg[2]),
       .CI (SUB_TC_OP71_n_21), .CO (SUB_TC_OP71_n_23), .S (X1_i_w[2]));
  ADDFX1 SUB_TC_OP71_g494__5477(.A (SUB_TC_OP71_n_13), .B (B_i_reg[1]),
       .CI (SUB_TC_OP71_n_18), .CO (SUB_TC_OP71_n_21), .S (X1_i_w[1]));
  OAI21X1 SUB_TC_OP71_g495__2398(.A0 (D_r_reg[0]), .A1
       (SUB_TC_OP71_n_6), .B0 (SUB_TC_OP71_n_18), .Y (X1_i_w[0]));
  MXI2XL SUB_TC_OP71_g496__5107(.A (SUB_TC_OP71_n_10), .B
       (B_i_reg[16]), .S0 (D_r_reg[16]), .Y (SUB_TC_OP71_n_19));
  NAND2XL SUB_TC_OP71_g497__6260(.A (D_r_reg[0]), .B (SUB_TC_OP71_n_6),
       .Y (SUB_TC_OP71_n_18));
  NOR2BX1 SUB_TC_OP71_g498__4319(.AN (D_r_reg[16]), .B (B_i_reg[16]),
       .Y (SUB_TC_OP71_n_17));
  OAI22X1 SUB_TC_OP73_g449__8428(.A0 (SUB_TC_OP73_n_17), .A1
       (SUB_TC_OP73_n_47), .B0 (x3_i_reg[15]), .B1 (SUB_TC_OP73_n_11),
       .Y (D_i[16]));
  OAI21X1 SUB_TC_OP73_g450__5526(.A0 (SUB_TC_OP73_n_18), .A1
       (SUB_TC_OP73_n_47), .B0 (SUB_TC_OP73_n_48), .Y (D_i[15]));
  NAND2XL SUB_TC_OP73_g451__6783(.A (SUB_TC_OP73_n_18), .B
       (SUB_TC_OP73_n_47), .Y (SUB_TC_OP73_n_48));
  ADDFX1 SUB_TC_OP73_g452__3680(.A (SUB_TC_OP73_n_4), .B
       (x1_i_reg[14]), .CI (SUB_TC_OP73_n_44), .CO (SUB_TC_OP73_n_47),
       .S (D_i[14]));
  ADDFX1 SUB_TC_OP73_g453__1617(.A (SUB_TC_OP73_n_12), .B
       (x1_i_reg[13]), .CI (SUB_TC_OP73_n_42), .CO (SUB_TC_OP73_n_44),
       .S (D_i[13]));
  ADDFX1 SUB_TC_OP73_g454__2802(.A (SUB_TC_OP73_n_15), .B
       (x1_i_reg[12]), .CI (SUB_TC_OP73_n_40), .CO (SUB_TC_OP73_n_42),
       .S (D_i[12]));
  ADDFX1 SUB_TC_OP73_g455__1705(.A (SUB_TC_OP73_n_8), .B
       (x1_i_reg[11]), .CI (SUB_TC_OP73_n_38), .CO (SUB_TC_OP73_n_40),
       .S (D_i[11]));
  ADDFX1 SUB_TC_OP73_g456__5122(.A (SUB_TC_OP73_n_6), .B
       (x1_i_reg[10]), .CI (SUB_TC_OP73_n_36), .CO (SUB_TC_OP73_n_38),
       .S (D_i[10]));
  ADDFX1 SUB_TC_OP73_g457__8246(.A (SUB_TC_OP73_n_3), .B (x1_i_reg[9]),
       .CI (SUB_TC_OP73_n_34), .CO (SUB_TC_OP73_n_36), .S (D_i[9]));
  ADDFX1 SUB_TC_OP73_g458__7098(.A (SUB_TC_OP73_n_14), .B
       (x1_i_reg[8]), .CI (SUB_TC_OP73_n_32), .CO (SUB_TC_OP73_n_34),
       .S (D_i[8]));
  ADDFX1 SUB_TC_OP73_g459__6131(.A (SUB_TC_OP73_n_13), .B
       (x1_i_reg[7]), .CI (SUB_TC_OP73_n_30), .CO (SUB_TC_OP73_n_32),
       .S (D_i[7]));
  ADDFX1 SUB_TC_OP73_g460__1881(.A (SUB_TC_OP73_n_7), .B (x1_i_reg[6]),
       .CI (SUB_TC_OP73_n_28), .CO (SUB_TC_OP73_n_30), .S (D_i[6]));
  ADDFX1 SUB_TC_OP73_g461__5115(.A (SUB_TC_OP73_n_10), .B
       (x1_i_reg[5]), .CI (SUB_TC_OP73_n_26), .CO (SUB_TC_OP73_n_28),
       .S (D_i[5]));
  ADDFX1 SUB_TC_OP73_g462__7482(.A (SUB_TC_OP73_n_0), .B (x1_i_reg[4]),
       .CI (SUB_TC_OP73_n_24), .CO (SUB_TC_OP73_n_26), .S (D_i[4]));
  ADDFX1 SUB_TC_OP73_g463__4733(.A (SUB_TC_OP73_n_1), .B (x1_i_reg[3]),
       .CI (SUB_TC_OP73_n_22), .CO (SUB_TC_OP73_n_24), .S (D_i[3]));
  ADDFX1 SUB_TC_OP73_g464__6161(.A (SUB_TC_OP73_n_9), .B (x1_i_reg[2]),
       .CI (SUB_TC_OP73_n_20), .CO (SUB_TC_OP73_n_22), .S (D_i[2]));
  ADDFX1 SUB_TC_OP73_g465__9315(.A (SUB_TC_OP73_n_2), .B (x1_i_reg[1]),
       .CI (SUB_TC_OP73_n_16), .CO (SUB_TC_OP73_n_20), .S (D_i[1]));
  OAI21X1 SUB_TC_OP73_g466__9945(.A0 (x3_i_reg[0]), .A1
       (SUB_TC_OP73_n_5), .B0 (SUB_TC_OP73_n_16), .Y (D_i[0]));
  MXI2XL SUB_TC_OP73_g467__2883(.A (SUB_TC_OP73_n_11), .B
       (x1_i_reg[15]), .S0 (x3_i_reg[15]), .Y (SUB_TC_OP73_n_18));
  NOR2BX1 SUB_TC_OP73_g468__2346(.AN (x3_i_reg[15]), .B (x1_i_reg[15]),
       .Y (SUB_TC_OP73_n_17));
  NAND2XL SUB_TC_OP73_g469__1666(.A (x3_i_reg[0]), .B
       (SUB_TC_OP73_n_5), .Y (SUB_TC_OP73_n_16));
  OAI22X1 SUB_TC_OP75_g449__7410(.A0 (SUB_TC_OP75_n_17), .A1
       (SUB_TC_OP75_n_47), .B0 (x3_r_reg[15]), .B1 (SUB_TC_OP75_n_11),
       .Y (D_r[16]));
  OAI21X1 SUB_TC_OP75_g450__6417(.A0 (SUB_TC_OP75_n_18), .A1
       (SUB_TC_OP75_n_47), .B0 (SUB_TC_OP75_n_48), .Y (D_r[15]));
  NAND2XL SUB_TC_OP75_g451__5477(.A (SUB_TC_OP75_n_18), .B
       (SUB_TC_OP75_n_47), .Y (SUB_TC_OP75_n_48));
  ADDFX1 SUB_TC_OP75_g452__2398(.A (SUB_TC_OP75_n_4), .B
       (x1_r_reg[14]), .CI (SUB_TC_OP75_n_44), .CO (SUB_TC_OP75_n_47),
       .S (D_r[14]));
  ADDFX1 SUB_TC_OP75_g453__5107(.A (SUB_TC_OP75_n_12), .B
       (x1_r_reg[13]), .CI (SUB_TC_OP75_n_42), .CO (SUB_TC_OP75_n_44),
       .S (D_r[13]));
  ADDFX1 SUB_TC_OP75_g454__6260(.A (SUB_TC_OP75_n_15), .B
       (x1_r_reg[12]), .CI (SUB_TC_OP75_n_40), .CO (SUB_TC_OP75_n_42),
       .S (D_r[12]));
  ADDFX1 SUB_TC_OP75_g455__4319(.A (SUB_TC_OP75_n_8), .B
       (x1_r_reg[11]), .CI (SUB_TC_OP75_n_38), .CO (SUB_TC_OP75_n_40),
       .S (D_r[11]));
  ADDFX1 SUB_TC_OP75_g456__8428(.A (SUB_TC_OP75_n_6), .B
       (x1_r_reg[10]), .CI (SUB_TC_OP75_n_36), .CO (SUB_TC_OP75_n_38),
       .S (D_r[10]));
  ADDFX1 SUB_TC_OP75_g457__5526(.A (SUB_TC_OP75_n_3), .B (x1_r_reg[9]),
       .CI (SUB_TC_OP75_n_34), .CO (SUB_TC_OP75_n_36), .S (D_r[9]));
  ADDFX1 SUB_TC_OP75_g458__6783(.A (SUB_TC_OP75_n_14), .B
       (x1_r_reg[8]), .CI (SUB_TC_OP75_n_32), .CO (SUB_TC_OP75_n_34),
       .S (D_r[8]));
  ADDFX1 SUB_TC_OP75_g459__3680(.A (SUB_TC_OP75_n_13), .B
       (x1_r_reg[7]), .CI (SUB_TC_OP75_n_30), .CO (SUB_TC_OP75_n_32),
       .S (D_r[7]));
  ADDFX1 SUB_TC_OP75_g460__1617(.A (SUB_TC_OP75_n_7), .B (x1_r_reg[6]),
       .CI (SUB_TC_OP75_n_28), .CO (SUB_TC_OP75_n_30), .S (D_r[6]));
  ADDFX1 SUB_TC_OP75_g461__2802(.A (SUB_TC_OP75_n_10), .B
       (x1_r_reg[5]), .CI (SUB_TC_OP75_n_26), .CO (SUB_TC_OP75_n_28),
       .S (D_r[5]));
  ADDFX1 SUB_TC_OP75_g462__1705(.A (SUB_TC_OP75_n_0), .B (x1_r_reg[4]),
       .CI (SUB_TC_OP75_n_24), .CO (SUB_TC_OP75_n_26), .S (D_r[4]));
  ADDFX1 SUB_TC_OP75_g463__5122(.A (SUB_TC_OP75_n_1), .B (x1_r_reg[3]),
       .CI (SUB_TC_OP75_n_22), .CO (SUB_TC_OP75_n_24), .S (D_r[3]));
  ADDFX1 SUB_TC_OP75_g464__8246(.A (SUB_TC_OP75_n_9), .B (x1_r_reg[2]),
       .CI (SUB_TC_OP75_n_20), .CO (SUB_TC_OP75_n_22), .S (D_r[2]));
  ADDFX1 SUB_TC_OP75_g465__7098(.A (SUB_TC_OP75_n_2), .B (x1_r_reg[1]),
       .CI (SUB_TC_OP75_n_16), .CO (SUB_TC_OP75_n_20), .S (D_r[1]));
  OAI21X1 SUB_TC_OP75_g466__6131(.A0 (x3_r_reg[0]), .A1
       (SUB_TC_OP75_n_5), .B0 (SUB_TC_OP75_n_16), .Y (D_r[0]));
  MXI2XL SUB_TC_OP75_g467__1881(.A (SUB_TC_OP75_n_11), .B
       (x1_r_reg[15]), .S0 (x3_r_reg[15]), .Y (SUB_TC_OP75_n_18));
  NOR2BX1 SUB_TC_OP75_g468__5115(.AN (x3_r_reg[15]), .B (x1_r_reg[15]),
       .Y (SUB_TC_OP75_n_17));
  NAND2XL SUB_TC_OP75_g469__7482(.A (x3_r_reg[0]), .B
       (SUB_TC_OP75_n_5), .Y (SUB_TC_OP75_n_16));
  OAI22X1 SUB_TC_OP77_g449__4733(.A0 (SUB_TC_OP77_n_17), .A1
       (SUB_TC_OP77_n_47), .B0 (x2_i_reg[15]), .B1 (SUB_TC_OP77_n_11),
       .Y (B_i[16]));
  OAI21X1 SUB_TC_OP77_g450__6161(.A0 (SUB_TC_OP77_n_18), .A1
       (SUB_TC_OP77_n_47), .B0 (SUB_TC_OP77_n_48), .Y (B_i[15]));
  NAND2XL SUB_TC_OP77_g451__9315(.A (SUB_TC_OP77_n_18), .B
       (SUB_TC_OP77_n_47), .Y (SUB_TC_OP77_n_48));
  ADDFX1 SUB_TC_OP77_g452__9945(.A (SUB_TC_OP77_n_4), .B
       (x0_i_reg[14]), .CI (SUB_TC_OP77_n_44), .CO (SUB_TC_OP77_n_47),
       .S (B_i[14]));
  ADDFX1 SUB_TC_OP77_g453__2883(.A (SUB_TC_OP77_n_12), .B
       (x0_i_reg[13]), .CI (SUB_TC_OP77_n_42), .CO (SUB_TC_OP77_n_44),
       .S (B_i[13]));
  ADDFX1 SUB_TC_OP77_g454__2346(.A (SUB_TC_OP77_n_15), .B
       (x0_i_reg[12]), .CI (SUB_TC_OP77_n_40), .CO (SUB_TC_OP77_n_42),
       .S (B_i[12]));
  ADDFX1 SUB_TC_OP77_g455__1666(.A (SUB_TC_OP77_n_8), .B
       (x0_i_reg[11]), .CI (SUB_TC_OP77_n_38), .CO (SUB_TC_OP77_n_40),
       .S (B_i[11]));
  ADDFX1 SUB_TC_OP77_g456__7410(.A (SUB_TC_OP77_n_6), .B
       (x0_i_reg[10]), .CI (SUB_TC_OP77_n_36), .CO (SUB_TC_OP77_n_38),
       .S (B_i[10]));
  ADDFX1 SUB_TC_OP77_g457__6417(.A (SUB_TC_OP77_n_3), .B (x0_i_reg[9]),
       .CI (SUB_TC_OP77_n_34), .CO (SUB_TC_OP77_n_36), .S (B_i[9]));
  ADDFX1 SUB_TC_OP77_g458__5477(.A (SUB_TC_OP77_n_14), .B
       (x0_i_reg[8]), .CI (SUB_TC_OP77_n_32), .CO (SUB_TC_OP77_n_34),
       .S (B_i[8]));
  ADDFX1 SUB_TC_OP77_g459__2398(.A (SUB_TC_OP77_n_13), .B
       (x0_i_reg[7]), .CI (SUB_TC_OP77_n_30), .CO (SUB_TC_OP77_n_32),
       .S (B_i[7]));
  ADDFX1 SUB_TC_OP77_g460__5107(.A (SUB_TC_OP77_n_7), .B (x0_i_reg[6]),
       .CI (SUB_TC_OP77_n_28), .CO (SUB_TC_OP77_n_30), .S (B_i[6]));
  ADDFX1 SUB_TC_OP77_g461__6260(.A (SUB_TC_OP77_n_10), .B
       (x0_i_reg[5]), .CI (SUB_TC_OP77_n_26), .CO (SUB_TC_OP77_n_28),
       .S (B_i[5]));
  ADDFX1 SUB_TC_OP77_g462__4319(.A (SUB_TC_OP77_n_0), .B (x0_i_reg[4]),
       .CI (SUB_TC_OP77_n_24), .CO (SUB_TC_OP77_n_26), .S (B_i[4]));
  ADDFX1 SUB_TC_OP77_g463__8428(.A (SUB_TC_OP77_n_1), .B (x0_i_reg[3]),
       .CI (SUB_TC_OP77_n_22), .CO (SUB_TC_OP77_n_24), .S (B_i[3]));
  ADDFX1 SUB_TC_OP77_g464__5526(.A (SUB_TC_OP77_n_9), .B (x0_i_reg[2]),
       .CI (SUB_TC_OP77_n_20), .CO (SUB_TC_OP77_n_22), .S (B_i[2]));
  ADDFX1 SUB_TC_OP77_g465__6783(.A (SUB_TC_OP77_n_2), .B (x0_i_reg[1]),
       .CI (SUB_TC_OP77_n_16), .CO (SUB_TC_OP77_n_20), .S (B_i[1]));
  OAI21X1 SUB_TC_OP77_g466__3680(.A0 (x2_i_reg[0]), .A1
       (SUB_TC_OP77_n_5), .B0 (SUB_TC_OP77_n_16), .Y (B_i[0]));
  MXI2XL SUB_TC_OP77_g467__1617(.A (SUB_TC_OP77_n_11), .B
       (x0_i_reg[15]), .S0 (x2_i_reg[15]), .Y (SUB_TC_OP77_n_18));
  NOR2BX1 SUB_TC_OP77_g468__2802(.AN (x2_i_reg[15]), .B (x0_i_reg[15]),
       .Y (SUB_TC_OP77_n_17));
  NAND2XL SUB_TC_OP77_g469__1705(.A (x2_i_reg[0]), .B
       (SUB_TC_OP77_n_5), .Y (SUB_TC_OP77_n_16));
  OAI22X1 SUB_TC_OP79_g449__5122(.A0 (SUB_TC_OP79_n_17), .A1
       (SUB_TC_OP79_n_47), .B0 (x2_r_reg[15]), .B1 (SUB_TC_OP79_n_11),
       .Y (B_r[16]));
  OAI21X1 SUB_TC_OP79_g450__8246(.A0 (SUB_TC_OP79_n_18), .A1
       (SUB_TC_OP79_n_47), .B0 (SUB_TC_OP79_n_48), .Y (B_r[15]));
  NAND2XL SUB_TC_OP79_g451__7098(.A (SUB_TC_OP79_n_18), .B
       (SUB_TC_OP79_n_47), .Y (SUB_TC_OP79_n_48));
  ADDFX1 SUB_TC_OP79_g452__6131(.A (SUB_TC_OP79_n_4), .B
       (x0_r_reg[14]), .CI (SUB_TC_OP79_n_44), .CO (SUB_TC_OP79_n_47),
       .S (B_r[14]));
  ADDFX1 SUB_TC_OP79_g453__1881(.A (SUB_TC_OP79_n_12), .B
       (x0_r_reg[13]), .CI (SUB_TC_OP79_n_42), .CO (SUB_TC_OP79_n_44),
       .S (B_r[13]));
  ADDFX1 SUB_TC_OP79_g454__5115(.A (SUB_TC_OP79_n_15), .B
       (x0_r_reg[12]), .CI (SUB_TC_OP79_n_40), .CO (SUB_TC_OP79_n_42),
       .S (B_r[12]));
  ADDFX1 SUB_TC_OP79_g455__7482(.A (SUB_TC_OP79_n_8), .B
       (x0_r_reg[11]), .CI (SUB_TC_OP79_n_38), .CO (SUB_TC_OP79_n_40),
       .S (B_r[11]));
  ADDFX1 SUB_TC_OP79_g456__4733(.A (SUB_TC_OP79_n_6), .B
       (x0_r_reg[10]), .CI (SUB_TC_OP79_n_36), .CO (SUB_TC_OP79_n_38),
       .S (B_r[10]));
  ADDFX1 SUB_TC_OP79_g457__6161(.A (SUB_TC_OP79_n_3), .B (x0_r_reg[9]),
       .CI (SUB_TC_OP79_n_34), .CO (SUB_TC_OP79_n_36), .S (B_r[9]));
  ADDFX1 SUB_TC_OP79_g458__9315(.A (SUB_TC_OP79_n_14), .B
       (x0_r_reg[8]), .CI (SUB_TC_OP79_n_32), .CO (SUB_TC_OP79_n_34),
       .S (B_r[8]));
  ADDFX1 SUB_TC_OP79_g459__9945(.A (SUB_TC_OP79_n_13), .B
       (x0_r_reg[7]), .CI (SUB_TC_OP79_n_30), .CO (SUB_TC_OP79_n_32),
       .S (B_r[7]));
  ADDFX1 SUB_TC_OP79_g460__2883(.A (SUB_TC_OP79_n_7), .B (x0_r_reg[6]),
       .CI (SUB_TC_OP79_n_28), .CO (SUB_TC_OP79_n_30), .S (B_r[6]));
  ADDFX1 SUB_TC_OP79_g461__2346(.A (SUB_TC_OP79_n_10), .B
       (x0_r_reg[5]), .CI (SUB_TC_OP79_n_26), .CO (SUB_TC_OP79_n_28),
       .S (B_r[5]));
  ADDFX1 SUB_TC_OP79_g462__1666(.A (SUB_TC_OP79_n_0), .B (x0_r_reg[4]),
       .CI (SUB_TC_OP79_n_24), .CO (SUB_TC_OP79_n_26), .S (B_r[4]));
  ADDFX1 SUB_TC_OP79_g463__7410(.A (SUB_TC_OP79_n_1), .B (x0_r_reg[3]),
       .CI (SUB_TC_OP79_n_22), .CO (SUB_TC_OP79_n_24), .S (B_r[3]));
  ADDFX1 SUB_TC_OP79_g464__6417(.A (SUB_TC_OP79_n_9), .B (x0_r_reg[2]),
       .CI (SUB_TC_OP79_n_20), .CO (SUB_TC_OP79_n_22), .S (B_r[2]));
  ADDFX1 SUB_TC_OP79_g465__5477(.A (SUB_TC_OP79_n_2), .B (x0_r_reg[1]),
       .CI (SUB_TC_OP79_n_16), .CO (SUB_TC_OP79_n_20), .S (B_r[1]));
  OAI21X1 SUB_TC_OP79_g466__2398(.A0 (x2_r_reg[0]), .A1
       (SUB_TC_OP79_n_5), .B0 (SUB_TC_OP79_n_16), .Y (B_r[0]));
  MXI2XL SUB_TC_OP79_g467__5107(.A (SUB_TC_OP79_n_11), .B
       (x0_r_reg[15]), .S0 (x2_r_reg[15]), .Y (SUB_TC_OP79_n_18));
  NOR2BX1 SUB_TC_OP79_g468__6260(.AN (x2_r_reg[15]), .B (x0_r_reg[15]),
       .Y (SUB_TC_OP79_n_17));
  NAND2XL SUB_TC_OP79_g469__4319(.A (x2_r_reg[0]), .B
       (SUB_TC_OP79_n_5), .Y (SUB_TC_OP79_n_16));
  DFFRX1 \D_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (D_i[7]), .Q
       (D_i_reg[7]), .QN (SUB_TC_OP_n_16));
  DFFRX1 \D_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (D_i[3]), .Q
       (D_i_reg[3]), .QN (SUB_TC_OP_n_15));
  DFFRX1 \D_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (D_i[2]), .Q
       (D_i_reg[2]), .QN (SUB_TC_OP_n_14));
  DFFRX1 \D_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (D_i[1]), .Q
       (D_i_reg[1]), .QN (SUB_TC_OP_n_13));
  DFFRX1 \D_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (D_i[14]), .Q
       (D_i_reg[14]), .QN (SUB_TC_OP_n_12));
  DFFRX1 \D_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (D_i[10]), .Q
       (D_i_reg[10]), .QN (SUB_TC_OP_n_11));
  DFFRX1 \B_r_reg_reg[16] (.RN (rst_n), .CK (clk), .D (B_r[16]), .Q
       (B_r_reg[16]), .QN (SUB_TC_OP_n_10));
  DFFRX1 \D_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (D_i[8]), .Q
       (D_i_reg[8]), .QN (SUB_TC_OP_n_9));
  DFFRX1 \D_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (D_i[11]), .Q
       (D_i_reg[11]), .QN (SUB_TC_OP_n_8));
  DFFRX1 \D_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (D_i[5]), .Q
       (D_i_reg[5]), .QN (SUB_TC_OP_n_7));
  DFFRX1 \B_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (B_r[0]), .Q
       (B_r_reg[0]), .QN (SUB_TC_OP_n_6));
  DFFRX1 \D_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (D_i[12]), .Q
       (D_i_reg[12]), .QN (SUB_TC_OP_n_5));
  DFFRX1 \D_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (D_i[4]), .Q
       (D_i_reg[4]), .QN (SUB_TC_OP_n_4));
  DFFRX1 \D_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (D_i[9]), .Q
       (D_i_reg[9]), .QN (SUB_TC_OP_n_3));
  DFFRX1 \D_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (D_i[15]), .Q
       (D_i_reg[15]), .QN (SUB_TC_OP_n_2));
  DFFRX1 \D_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (D_i[6]), .Q
       (D_i_reg[6]), .QN (SUB_TC_OP_n_1));
  DFFRX1 \D_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (D_i[13]), .Q
       (D_i_reg[13]), .QN (SUB_TC_OP_n_0));
  DFFRX1 \C_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (C_i[7]), .Q
       (C_i_reg[7]), .QN (SUB_TC_OP67_n_16));
  DFFRX1 \C_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (C_i[3]), .Q
       (C_i_reg[3]), .QN (SUB_TC_OP67_n_15));
  DFFRX1 \C_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (C_i[2]), .Q
       (C_i_reg[2]), .QN (SUB_TC_OP67_n_14));
  DFFRX1 \C_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (C_i[1]), .Q
       (C_i_reg[1]), .QN (SUB_TC_OP67_n_13));
  DFFRX1 \C_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (C_i[14]), .Q
       (C_i_reg[14]), .QN (SUB_TC_OP67_n_12));
  DFFRX1 \C_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (C_i[10]), .Q
       (C_i_reg[10]), .QN (SUB_TC_OP67_n_11));
  DFFRX1 \A_i_reg_reg[16] (.RN (rst_n), .CK (clk), .D (A_i[16]), .Q
       (A_i_reg[16]), .QN (SUB_TC_OP67_n_10));
  DFFRX1 \C_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (C_i[8]), .Q
       (C_i_reg[8]), .QN (SUB_TC_OP67_n_9));
  DFFRX1 \C_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (C_i[11]), .Q
       (C_i_reg[11]), .QN (SUB_TC_OP67_n_8));
  DFFRX1 \C_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (C_i[5]), .Q
       (C_i_reg[5]), .QN (SUB_TC_OP67_n_7));
  DFFRX1 \A_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (A_i[0]), .Q
       (A_i_reg[0]), .QN (SUB_TC_OP67_n_6));
  DFFRX1 \C_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (C_i[12]), .Q
       (C_i_reg[12]), .QN (SUB_TC_OP67_n_5));
  DFFRX1 \C_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (C_i[4]), .Q
       (C_i_reg[4]), .QN (SUB_TC_OP67_n_4));
  DFFRX1 \C_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (C_i[9]), .Q
       (C_i_reg[9]), .QN (SUB_TC_OP67_n_3));
  DFFRX1 \C_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (C_i[15]), .Q
       (C_i_reg[15]), .QN (SUB_TC_OP67_n_2));
  DFFRX1 \C_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (C_i[6]), .Q
       (C_i_reg[6]), .QN (SUB_TC_OP67_n_1));
  DFFRX1 \C_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (C_i[13]), .Q
       (C_i_reg[13]), .QN (SUB_TC_OP67_n_0));
  DFFRX1 \C_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (C_r[7]), .Q
       (C_r_reg[7]), .QN (SUB_TC_OP69_n_16));
  DFFRX1 \C_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (C_r[3]), .Q
       (C_r_reg[3]), .QN (SUB_TC_OP69_n_15));
  DFFRX1 \C_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (C_r[2]), .Q
       (C_r_reg[2]), .QN (SUB_TC_OP69_n_14));
  DFFRX1 \C_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (C_r[1]), .Q
       (C_r_reg[1]), .QN (SUB_TC_OP69_n_13));
  DFFRX1 \C_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (C_r[14]), .Q
       (C_r_reg[14]), .QN (SUB_TC_OP69_n_12));
  DFFRX1 \C_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (C_r[10]), .Q
       (C_r_reg[10]), .QN (SUB_TC_OP69_n_11));
  DFFRX1 \A_r_reg_reg[16] (.RN (rst_n), .CK (clk), .D (A_r[16]), .Q
       (A_r_reg[16]), .QN (SUB_TC_OP69_n_10));
  DFFRX1 \C_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (C_r[8]), .Q
       (C_r_reg[8]), .QN (SUB_TC_OP69_n_9));
  DFFRX1 \C_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (C_r[11]), .Q
       (C_r_reg[11]), .QN (SUB_TC_OP69_n_8));
  DFFRX1 \C_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (C_r[5]), .Q
       (C_r_reg[5]), .QN (SUB_TC_OP69_n_7));
  DFFRX1 \A_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (A_r[0]), .Q
       (A_r_reg[0]), .QN (SUB_TC_OP69_n_6));
  DFFRX1 \C_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (C_r[12]), .Q
       (C_r_reg[12]), .QN (SUB_TC_OP69_n_5));
  DFFRX1 \C_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (C_r[4]), .Q
       (C_r_reg[4]), .QN (SUB_TC_OP69_n_4));
  DFFRX1 \C_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (C_r[9]), .Q
       (C_r_reg[9]), .QN (SUB_TC_OP69_n_3));
  DFFRX1 \C_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (C_r[15]), .Q
       (C_r_reg[15]), .QN (SUB_TC_OP69_n_2));
  DFFRX1 \C_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (C_r[6]), .Q
       (C_r_reg[6]), .QN (SUB_TC_OP69_n_1));
  DFFRX1 \C_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (C_r[13]), .Q
       (C_r_reg[13]), .QN (SUB_TC_OP69_n_0));
  DFFRX1 \D_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (D_r[7]), .Q
       (D_r_reg[7]), .QN (SUB_TC_OP71_n_16));
  DFFRX1 \D_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (D_r[3]), .Q
       (D_r_reg[3]), .QN (SUB_TC_OP71_n_15));
  DFFRX1 \D_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (D_r[2]), .Q
       (D_r_reg[2]), .QN (SUB_TC_OP71_n_14));
  DFFRX1 \D_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (D_r[1]), .Q
       (D_r_reg[1]), .QN (SUB_TC_OP71_n_13));
  DFFRX1 \D_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (D_r[14]), .Q
       (D_r_reg[14]), .QN (SUB_TC_OP71_n_12));
  DFFRX1 \D_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (D_r[10]), .Q
       (D_r_reg[10]), .QN (SUB_TC_OP71_n_11));
  DFFRX1 \B_i_reg_reg[16] (.RN (rst_n), .CK (clk), .D (B_i[16]), .Q
       (B_i_reg[16]), .QN (SUB_TC_OP71_n_10));
  DFFRX1 \D_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (D_r[8]), .Q
       (D_r_reg[8]), .QN (SUB_TC_OP71_n_9));
  DFFRX1 \D_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (D_r[11]), .Q
       (D_r_reg[11]), .QN (SUB_TC_OP71_n_8));
  DFFRX1 \D_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (D_r[5]), .Q
       (D_r_reg[5]), .QN (SUB_TC_OP71_n_7));
  DFFRX1 \B_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (B_i[0]), .Q
       (B_i_reg[0]), .QN (SUB_TC_OP71_n_6));
  DFFRX1 \D_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (D_r[12]), .Q
       (D_r_reg[12]), .QN (SUB_TC_OP71_n_5));
  DFFRX1 \D_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (D_r[4]), .Q
       (D_r_reg[4]), .QN (SUB_TC_OP71_n_4));
  DFFRX1 \D_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (D_r[9]), .Q
       (D_r_reg[9]), .QN (SUB_TC_OP71_n_3));
  DFFRX1 \D_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (D_r[15]), .Q
       (D_r_reg[15]), .QN (SUB_TC_OP71_n_2));
  DFFRX1 \D_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (D_r[6]), .Q
       (D_r_reg[6]), .QN (SUB_TC_OP71_n_1));
  DFFRX1 \D_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (D_r[13]), .Q
       (D_r_reg[13]), .QN (SUB_TC_OP71_n_0));
  DFFRX1 \x3_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (x3_i[12]), .Q
       (x3_i_reg[12]), .QN (SUB_TC_OP73_n_15));
  DFFRX1 \x3_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (x3_i[8]), .Q
       (x3_i_reg[8]), .QN (SUB_TC_OP73_n_14));
  DFFRX1 \x3_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (x3_i[7]), .Q
       (x3_i_reg[7]), .QN (SUB_TC_OP73_n_13));
  DFFRX1 \x3_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (x3_i[13]), .Q
       (x3_i_reg[13]), .QN (SUB_TC_OP73_n_12));
  DFFRX1 \x1_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (x1_i[15]), .Q
       (x1_i_reg[15]), .QN (SUB_TC_OP73_n_11));
  DFFRX1 \x3_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (x3_i[5]), .Q
       (x3_i_reg[5]), .QN (SUB_TC_OP73_n_10));
  DFFRX1 \x3_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (x3_i[2]), .Q
       (x3_i_reg[2]), .QN (SUB_TC_OP73_n_9));
  DFFRX1 \x3_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (x3_i[11]), .Q
       (x3_i_reg[11]), .QN (SUB_TC_OP73_n_8));
  DFFRX1 \x3_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (x3_i[6]), .Q
       (x3_i_reg[6]), .QN (SUB_TC_OP73_n_7));
  DFFRX1 \x3_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (x3_i[10]), .Q
       (x3_i_reg[10]), .QN (SUB_TC_OP73_n_6));
  DFFRX1 \x1_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (x1_i[0]), .Q
       (x1_i_reg[0]), .QN (SUB_TC_OP73_n_5));
  DFFRX1 \x3_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (x3_i[14]), .Q
       (x3_i_reg[14]), .QN (SUB_TC_OP73_n_4));
  DFFRX1 \x3_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (x3_i[9]), .Q
       (x3_i_reg[9]), .QN (SUB_TC_OP73_n_3));
  DFFRX1 \x3_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (x3_i[1]), .Q
       (x3_i_reg[1]), .QN (SUB_TC_OP73_n_2));
  DFFRX1 \x3_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (x3_i[3]), .Q
       (x3_i_reg[3]), .QN (SUB_TC_OP73_n_1));
  DFFRX1 \x3_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (x3_i[4]), .Q
       (x3_i_reg[4]), .QN (SUB_TC_OP73_n_0));
  DFFRX1 \x3_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (x3_r[12]), .Q
       (x3_r_reg[12]), .QN (SUB_TC_OP75_n_15));
  DFFRX1 \x3_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (x3_r[8]), .Q
       (x3_r_reg[8]), .QN (SUB_TC_OP75_n_14));
  DFFRX1 \x3_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (x3_r[7]), .Q
       (x3_r_reg[7]), .QN (SUB_TC_OP75_n_13));
  DFFRX1 \x3_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (x3_r[13]), .Q
       (x3_r_reg[13]), .QN (SUB_TC_OP75_n_12));
  DFFRX1 \x1_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (x1_r[15]), .Q
       (x1_r_reg[15]), .QN (SUB_TC_OP75_n_11));
  DFFRX1 \x3_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (x3_r[5]), .Q
       (x3_r_reg[5]), .QN (SUB_TC_OP75_n_10));
  DFFRX1 \x3_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (x3_r[2]), .Q
       (x3_r_reg[2]), .QN (SUB_TC_OP75_n_9));
  DFFRX1 \x3_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (x3_r[11]), .Q
       (x3_r_reg[11]), .QN (SUB_TC_OP75_n_8));
  DFFRX1 \x3_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (x3_r[6]), .Q
       (x3_r_reg[6]), .QN (SUB_TC_OP75_n_7));
  DFFRX1 \x3_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (x3_r[10]), .Q
       (x3_r_reg[10]), .QN (SUB_TC_OP75_n_6));
  DFFRX1 \x1_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (x1_r[0]), .Q
       (x1_r_reg[0]), .QN (SUB_TC_OP75_n_5));
  DFFRX1 \x3_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (x3_r[14]), .Q
       (x3_r_reg[14]), .QN (SUB_TC_OP75_n_4));
  DFFRX1 \x3_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (x3_r[9]), .Q
       (x3_r_reg[9]), .QN (SUB_TC_OP75_n_3));
  DFFRX1 \x3_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (x3_r[1]), .Q
       (x3_r_reg[1]), .QN (SUB_TC_OP75_n_2));
  DFFRX1 \x3_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (x3_r[3]), .Q
       (x3_r_reg[3]), .QN (SUB_TC_OP75_n_1));
  DFFRX1 \x3_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (x3_r[4]), .Q
       (x3_r_reg[4]), .QN (SUB_TC_OP75_n_0));
  DFFRX1 \x2_i_reg_reg[12] (.RN (rst_n), .CK (clk), .D (x2_i[12]), .Q
       (x2_i_reg[12]), .QN (SUB_TC_OP77_n_15));
  DFFRX1 \x2_i_reg_reg[8] (.RN (rst_n), .CK (clk), .D (x2_i[8]), .Q
       (x2_i_reg[8]), .QN (SUB_TC_OP77_n_14));
  DFFRX1 \x2_i_reg_reg[7] (.RN (rst_n), .CK (clk), .D (x2_i[7]), .Q
       (x2_i_reg[7]), .QN (SUB_TC_OP77_n_13));
  DFFRX1 \x2_i_reg_reg[13] (.RN (rst_n), .CK (clk), .D (x2_i[13]), .Q
       (x2_i_reg[13]), .QN (SUB_TC_OP77_n_12));
  DFFRX1 \x0_i_reg_reg[15] (.RN (rst_n), .CK (clk), .D (x0_i[15]), .Q
       (x0_i_reg[15]), .QN (SUB_TC_OP77_n_11));
  DFFRX1 \x2_i_reg_reg[5] (.RN (rst_n), .CK (clk), .D (x2_i[5]), .Q
       (x2_i_reg[5]), .QN (SUB_TC_OP77_n_10));
  DFFRX1 \x2_i_reg_reg[2] (.RN (rst_n), .CK (clk), .D (x2_i[2]), .Q
       (x2_i_reg[2]), .QN (SUB_TC_OP77_n_9));
  DFFRX1 \x2_i_reg_reg[11] (.RN (rst_n), .CK (clk), .D (x2_i[11]), .Q
       (x2_i_reg[11]), .QN (SUB_TC_OP77_n_8));
  DFFRX1 \x2_i_reg_reg[6] (.RN (rst_n), .CK (clk), .D (x2_i[6]), .Q
       (x2_i_reg[6]), .QN (SUB_TC_OP77_n_7));
  DFFRX1 \x2_i_reg_reg[10] (.RN (rst_n), .CK (clk), .D (x2_i[10]), .Q
       (x2_i_reg[10]), .QN (SUB_TC_OP77_n_6));
  DFFRX1 \x0_i_reg_reg[0] (.RN (rst_n), .CK (clk), .D (x0_i[0]), .Q
       (x0_i_reg[0]), .QN (SUB_TC_OP77_n_5));
  DFFRX1 \x2_i_reg_reg[14] (.RN (rst_n), .CK (clk), .D (x2_i[14]), .Q
       (x2_i_reg[14]), .QN (SUB_TC_OP77_n_4));
  DFFRX1 \x2_i_reg_reg[9] (.RN (rst_n), .CK (clk), .D (x2_i[9]), .Q
       (x2_i_reg[9]), .QN (SUB_TC_OP77_n_3));
  DFFRX1 \x2_i_reg_reg[1] (.RN (rst_n), .CK (clk), .D (x2_i[1]), .Q
       (x2_i_reg[1]), .QN (SUB_TC_OP77_n_2));
  DFFRX1 \x2_i_reg_reg[3] (.RN (rst_n), .CK (clk), .D (x2_i[3]), .Q
       (x2_i_reg[3]), .QN (SUB_TC_OP77_n_1));
  DFFRX1 \x2_i_reg_reg[4] (.RN (rst_n), .CK (clk), .D (x2_i[4]), .Q
       (x2_i_reg[4]), .QN (SUB_TC_OP77_n_0));
  DFFRX1 \x2_r_reg_reg[12] (.RN (rst_n), .CK (clk), .D (x2_r[12]), .Q
       (x2_r_reg[12]), .QN (SUB_TC_OP79_n_15));
  DFFRX1 \x2_r_reg_reg[8] (.RN (rst_n), .CK (clk), .D (x2_r[8]), .Q
       (x2_r_reg[8]), .QN (SUB_TC_OP79_n_14));
  DFFRX1 \x2_r_reg_reg[7] (.RN (rst_n), .CK (clk), .D (x2_r[7]), .Q
       (x2_r_reg[7]), .QN (SUB_TC_OP79_n_13));
  DFFRX1 \x2_r_reg_reg[13] (.RN (rst_n), .CK (clk), .D (x2_r[13]), .Q
       (x2_r_reg[13]), .QN (SUB_TC_OP79_n_12));
  DFFRX1 \x0_r_reg_reg[15] (.RN (rst_n), .CK (clk), .D (x0_r[15]), .Q
       (x0_r_reg[15]), .QN (SUB_TC_OP79_n_11));
  DFFRX1 \x2_r_reg_reg[5] (.RN (rst_n), .CK (clk), .D (x2_r[5]), .Q
       (x2_r_reg[5]), .QN (SUB_TC_OP79_n_10));
  DFFRX1 \x2_r_reg_reg[2] (.RN (rst_n), .CK (clk), .D (x2_r[2]), .Q
       (x2_r_reg[2]), .QN (SUB_TC_OP79_n_9));
  DFFRX1 \x2_r_reg_reg[11] (.RN (rst_n), .CK (clk), .D (x2_r[11]), .Q
       (x2_r_reg[11]), .QN (SUB_TC_OP79_n_8));
  DFFRX1 \x2_r_reg_reg[6] (.RN (rst_n), .CK (clk), .D (x2_r[6]), .Q
       (x2_r_reg[6]), .QN (SUB_TC_OP79_n_7));
  DFFRX1 \x2_r_reg_reg[10] (.RN (rst_n), .CK (clk), .D (x2_r[10]), .Q
       (x2_r_reg[10]), .QN (SUB_TC_OP79_n_6));
  DFFRX1 \x0_r_reg_reg[0] (.RN (rst_n), .CK (clk), .D (x0_r[0]), .Q
       (x0_r_reg[0]), .QN (SUB_TC_OP79_n_5));
  DFFRX1 \x2_r_reg_reg[14] (.RN (rst_n), .CK (clk), .D (x2_r[14]), .Q
       (x2_r_reg[14]), .QN (SUB_TC_OP79_n_4));
  DFFRX1 \x2_r_reg_reg[9] (.RN (rst_n), .CK (clk), .D (x2_r[9]), .Q
       (x2_r_reg[9]), .QN (SUB_TC_OP79_n_3));
  DFFRX1 \x2_r_reg_reg[1] (.RN (rst_n), .CK (clk), .D (x2_r[1]), .Q
       (x2_r_reg[1]), .QN (SUB_TC_OP79_n_2));
  DFFRX1 \x2_r_reg_reg[3] (.RN (rst_n), .CK (clk), .D (x2_r[3]), .Q
       (x2_r_reg[3]), .QN (SUB_TC_OP79_n_1));
  DFFRX1 \x2_r_reg_reg[4] (.RN (rst_n), .CK (clk), .D (x2_r[4]), .Q
       (x2_r_reg[4]), .QN (SUB_TC_OP79_n_0));
endmodule

